// Generated by scripts/check-execution-bindings.mjs --write; edit Rust owners instead.

/**
 * Value-only admission result; policy/rule/approver details remain in privileged audit.
 *
 * This interface was referenced by `ExecutionTaskDetails`'s JSON-Schema
 * via the `definition` "AdmissionStatus".
 */
export type AdmissionStatus = "admitted" | "denied" | "approvalRequired";
/**
 * Verified assessment of the whole controlled attempt, not text from tool output.
 *
 * This interface was referenced by `ExecutionTaskDetails`'s JSON-Schema
 * via the `definition` "EffectAssessment".
 */
export type EffectAssessment =
  | "noEffect"
  | "satisfied"
  | "notSatisfied"
  | "unknown";
/**
 * Execution attempt correlation identity.
 *
 * This interface was referenced by `ExecutionTaskDetails`'s JSON-Schema
 * via the `definition` "AttemptId".
 */
export type AttemptId = string;
/**
 * Closed first-delivery diagnostics. These are not observations of termination or effects.
 *
 * This interface was referenced by `ExecutionTaskDetails`'s JSON-Schema
 * via the `definition` "DispatchCause".
 */
export type DispatchCause =
  | "capabilityUnavailable"
  | "clockUnavailable"
  | "cancelled"
  | {
      limit: LimitReason;
    }
  | "staleRevision"
  | "runnerMismatch"
  | "configurationUnavailable"
  | "authorityUnavailable"
  | "lifecycleChanged"
  | "runnerRejected"
  | "deliveryUnknown"
  | "runnerError";
/**
 * Explicit reason a validity or cumulative budget bound prevents work.
 *
 * This interface was referenced by `ExecutionTaskDetails`'s JSON-Schema
 * via the `definition` "LimitReason".
 */
export type LimitReason =
  | "notYetValid"
  | "expired"
  | "timeout"
  | "output"
  | "attempts";
/**
 * Safe software diagnostic; contains no paths, source coordinates or captured output.
 *
 * This interface was referenced by `ExecutionTaskDetails`'s JSON-Schema
 * via the `definition` "SoftwareDiagnostic".
 */
export type SoftwareDiagnostic =
  | "awaitingDetection"
  | "restartPending"
  | "detectionUnavailable"
  | "unrecognizedVersion"
  | "detectionBudgetExceeded"
  | "desiredStateObserved"
  | "desiredStateMissing"
  | "cleanupPending"
  | "cleanupUnverified";
/**
 * Closed stop request diagnostics. Neither variant is a termination/effect observation.
 *
 * This interface was referenced by `ExecutionTaskDetails`'s JSON-Schema
 * via the `definition` "StopOutcome".
 */
export type StopOutcome = "acknowledged" | "failed";
/**
 * Safe counts only; individual paths and network destinations remain protected.
 *
 * This interface was referenced by `ExecutionTaskDetails`'s JSON-Schema
 * via the `definition` "AccessSummary".
 */
export type AccessSummary =
  | {
      kind: "osIdentity";
    }
  | {
      /**
       * Required child process allowance.
       */
      allowChildProcesses: boolean;
      kind: "restricted";
      /**
       * Whether networking is completely denied.
       */
      networkDenied: boolean;
      /**
       * Number of exact allowlisted destinations; never their values.
       */
      networkDestinationCount: number;
      /**
       * Number of declared read paths.
       */
      readPathCount: number;
      /**
       * Required isolation; this is not an observation that enforcement succeeded.
       */
      requireSandbox: boolean;
      /**
       * Number of declared write paths.
       */
      writePathCount: number;
    };
/**
 * Product actor reference, not an authenticated principal.
 *
 * This interface was referenced by `ExecutionTaskDetails`'s JSON-Schema
 * via the `definition` "ActorId".
 */
export type ActorId = string;
/**
 * Separate namespaces: none of these serializable references authenticates its issuer.
 *
 * This interface was referenced by `ExecutionTaskDetails`'s JSON-Schema
 * via the `definition` "Authority".
 */
export type Authority =
  | {
      /**
       * Authority reference in this variant namespace; no proof of issuer authenticity.
       */
      id: string;
      kind: "local";
    }
  | {
      /**
       * Authority reference in this variant namespace; no proof of issuer authenticity.
       */
      id: string;
      kind: "enterprise";
      /**
       * Explicit enterprise tenant reference; local/test authority never fabricates a tenant.
       */
      tenant: string;
    }
  | {
      /**
       * Authority reference in this variant namespace; no proof of issuer authenticity.
       */
      id: string;
      kind: "test";
    };
/**
 * Device reference, not verified registration evidence.
 *
 * This interface was referenced by `ExecutionTaskDetails`'s JSON-Schema
 * via the `definition` "DeviceId".
 */
export type DeviceId = string;
/**
 * Lowercase SHA-256 bytes expressed as hex; a digest alone grants no trust.
 *
 * This interface was referenced by `ExecutionTaskDetails`'s JSON-Schema
 * via the `definition` "Digest".
 */
export type Digest = string;
/**
 * Recorded observation category. None of these references verifies a real-world effect.
 *
 * This interface was referenced by `ExecutionTaskDetails`'s JSON-Schema
 * via the `definition` "EvidenceKind".
 */
export type EvidenceKind = "testResult" | "processExited" | "stateObserved";
/**
 * Explicit execution provenance; test effects never become real effects.
 *
 * This interface was referenced by `ExecutionTaskDetails`'s JSON-Schema
 * via the `definition` "ExecutionMode".
 */
export type ExecutionMode = "test" | "real";
/**
 * Safe execution semantics for task presentation; it never grants execution permission.
 *
 * This interface was referenced by `ExecutionTaskDetails`'s JSON-Schema
 * via the `definition` "ExecutionSummary".
 */
export type ExecutionSummary =
  | {
      kind: "process";
    }
  | {
      /**
       * Selected platform adapter.
       */
      adapter:
        | "msi"
        | "winget"
        | "pkg"
        | "homebrew"
        | "windowsBundle"
        | "macosBundle";
      kind: "software";
      /**
       * Selected mutation.
       */
      mutation: "install" | "upgrade" | "downgrade" | "uninstall";
    };
/**
 * Opaque local reference identifier; syntax validity is not authenticity.
 *
 * This interface was referenced by `ExecutionTaskDetails`'s JSON-Schema
 * via the `definition` "Id".
 */
export type Id = string;
/**
 * Request origin and account provenance; never grants the product actor additional authority.
 *
 * This interface was referenced by `ExecutionTaskDetails`'s JSON-Schema
 * via the `definition` "Initiator".
 */
export type Initiator =
  | {
      kind: "human";
      osSession: OsSessionRef;
    }
  | {
      config: VersionedRef1;
      /**
       * Originating AI conversation reference in the provider namespace.
       */
      conversation: string;
      kind: "ai";
      osSession: OsSessionRef1;
      /**
       * Provider namespace, independent of product authentication.
       */
      provider: string;
      /**
       * Originating tool-call reference; cannot act as a product approval.
       */
      toolCall: string;
    }
  | {
      kind: "policy";
      policy: VersionedRef2;
    };
/**
 * This interface was referenced by `ExecutionTaskDetails`'s JSON-Schema
 * via the `definition` "LocalContractV4".
 */
export type LocalContractV4 = 4;
/**
 * One possible mutation, not a queued workflow step.
 *
 * This interface was referenced by `ExecutionTaskDetails`'s JSON-Schema
 * via the `definition` "MutationKind".
 */
export type MutationKind = "install" | "upgrade" | "downgrade" | "uninstall";
/**
 * Quality of the captured result, independent from the exit code.
 *
 * This interface was referenced by `ExecutionTaskDetails`'s JSON-Schema
 * via the `definition` "OutputQuality".
 */
export type OutputQuality = "complete" | "truncated" | "failed" | "partial";
/**
 * Target OS semantics for validation; an enum value is not a platform support claim.
 *
 * This interface was referenced by `ExecutionTaskDetails`'s JSON-Schema
 * via the `definition` "Platform".
 */
export type Platform = "windows" | "macos" | "linux";
/**
 * Why a bounded process owner stopped collecting output.
 *
 * This interface was referenced by `ExecutionTaskDetails`'s JSON-Schema
 * via the `definition` "ProcessEnd".
 */
export type ProcessEnd =
  | "rejected"
  | "exited"
  | "cancelled"
  | "timedOut"
  | "outputLimit"
  | "unknown";
/**
 * Closed, value-free mechanism diagnosis, independent of cancellation, exit and effect.
 *
 * This interface was referenced by `ExecutionTaskDetails`'s JSON-Schema
 * via the `definition` "ProcessFailureKind".
 */
export type ProcessFailureKind =
  | "none"
  | "denied"
  | "unbound"
  | "capability"
  | "unsupported"
  | "invalidInput"
  | "capacity"
  | "conflict"
  | "unavailable"
  | "runtime"
  | "spawn"
  | "inputDelivery"
  | "capture"
  | "supervision"
  | "outputValidation";
/**
 * Local execution request identity.
 *
 * This interface was referenced by `ExecutionTaskDetails`'s JSON-Schema
 * via the `definition` "RequestId".
 */
export type RequestId = string;
/**
 * Requested execution identity; authorization and actual identity switching are external.
 *
 * This interface was referenced by `ExecutionTaskDetails`'s JSON-Schema
 * via the `definition` "RunAs".
 */
export type RunAs =
  | {
      account: OsAccountRef1;
      kind: "user";
    }
  | {
      kind: "system";
      /**
       * OS namespace of this reference or target; does not assert platform support.
       */
      platform: "windows" | "macos" | "linux";
    };
/**
 * Required target user-session availability, independent of the originating login.
 *
 * This interface was referenced by `ExecutionTaskDetails`'s JSON-Schema
 * via the `definition` "SessionRequirement".
 */
export type SessionRequirement =
  | {
      kind: "notRequired";
    }
  | {
      account: OsAccountRef2;
      kind: "activeUser";
    };
/**
 * The supported software adapters. No plugin names or command strings are accepted.
 *
 * This interface was referenced by `ExecutionTaskDetails`'s JSON-Schema
 * via the `definition` "SoftwareKind".
 */
export type SoftwareKind =
  | "msi"
  | "winget"
  | "pkg"
  | "homebrew"
  | "windowsBundle"
  | "macosBundle";
/**
 * Device-wide or explicit-user scope of the requested operation.
 *
 * This interface was referenced by `ExecutionTaskDetails`'s JSON-Schema
 * via the `definition` "TargetScope".
 */
export type TargetScope =
  | {
      kind: "device";
    }
  | {
      account: OsAccountRef3;
      kind: "user";
    };
/**
 * Safe presentation of C09 facts, not a second persisted state machine.
 *
 * This interface was referenced by `ExecutionTaskDetails`'s JSON-Schema
 * via the `definition` "TaskPhase".
 */
export type TaskPhase =
  | "waiting"
  | "admissionDenied"
  | "approvalRequired"
  | "confirmationRequired"
  | "accepted"
  | "running"
  | "outcomeUnknown"
  | "executionEnded"
  | "verified"
  | "failedBeforeDispatch"
  | "cancelled";

/**
 * One authorized record read provides both lifecycle status and frozen plan facts.
 */
export interface ExecutionTaskDetails {
  action: FrozenExecutionSummary;
  status: ExecutionStatus;
}
/**
 * Redacted frozen plan bound to that lifecycle.
 */
export interface FrozenExecutionSummary {
  /**
   * Restrictions summarized without individual private values.
   */
  access:
    | {
        kind: "osIdentity";
      }
    | {
        /**
         * Required child process allowance.
         */
        allowChildProcesses: boolean;
        kind: "restricted";
        /**
         * Whether networking is completely denied.
         */
        networkDenied: boolean;
        /**
         * Number of exact allowlisted destinations; never their values.
         */
        networkDestinationCount: number;
        /**
         * Number of declared read paths.
         */
        readPathCount: number;
        /**
         * Required isolation; this is not an observation that enforcement succeeded.
         */
        requireSandbox: boolean;
        /**
         * Number of declared write paths.
         */
        writePathCount: number;
      };
  /**
   * Permission-bearing principal; not the model account.
   */
  actor: string;
  artifact: ExactArtifactRef;
  /**
   * Product authority bound to the exact plan.
   */
  authority:
    | {
        /**
         * Authority reference in this variant namespace; no proof of issuer authenticity.
         */
        id: string;
        kind: "local";
      }
    | {
        /**
         * Authority reference in this variant namespace; no proof of issuer authenticity.
         */
        id: string;
        kind: "enterprise";
        /**
         * Explicit enterprise tenant reference; local/test authority never fabricates a tenant.
         */
        tenant: string;
      }
    | {
        /**
         * Authority reference in this variant namespace; no proof of issuer authenticity.
         */
        id: string;
        kind: "test";
      };
  budget: ExecutionBudget;
  /**
   * Digest covers the complete original plan, including omitted private values.
   */
  contentDigest: string;
  /**
   * Closed execution kind without private software paths or source inputs.
   */
  execution:
    | {
        kind: "process";
      }
    | {
        /**
         * Selected platform adapter.
         */
        adapter:
          | "msi"
          | "winget"
          | "pkg"
          | "homebrew"
          | "windowsBundle"
          | "macosBundle";
        kind: "software";
        /**
         * Selected mutation.
         */
        mutation: "install" | "upgrade" | "downgrade" | "uninstall";
      };
  /**
   * Human or AI origin, without granting execution permission.
   */
  initiator:
    | {
        kind: "human";
        osSession: OsSessionRef;
      }
    | {
        config: VersionedRef1;
        /**
         * Originating AI conversation reference in the provider namespace.
         */
        conversation: string;
        kind: "ai";
        osSession: OsSessionRef1;
        /**
         * Provider namespace, independent of product authentication.
         */
        provider: string;
        /**
         * Originating tool-call reference; cannot act as a product approval.
         */
        toolCall: string;
      }
    | {
        kind: "policy";
        policy: VersionedRef2;
      };
  interpreter: InterpreterRef;
  operation: Operation;
  policy: VersionedRef5;
  /**
   * Exact frozen plan identity.
   */
  requestId: string;
  /**
   * Explicit execution identity; never inferred from a provider login.
   */
  runAs:
    | {
        account: OsAccountRef1;
        kind: "user";
      }
    | {
        kind: "system";
        /**
         * OS namespace of this reference or target; does not assert platform support.
         */
        platform: "windows" | "macos" | "linux";
      };
  /**
   * Version of the frozen execution plan, independent of the AI wire version.
   */
  schemaVersion: 4;
  /**
   * Required target user session.
   */
  sessionRequirement:
    | {
        kind: "notRequired";
      }
    | {
        account: OsAccountRef2;
        kind: "activeUser";
      };
  target: Target;
  validity: ValidityWindow;
}
/**
 * Exact artifact revision and content hash.
 */
export interface ExactArtifactRef {
  resource: VersionedRef;
  /**
   * Expected content SHA-256. The adapter must verify the actual bytes before use.
   */
  sha256: string;
}
/**
 * Exact resource ID and revision; no latest-version lookup is performed here.
 */
export interface VersionedRef {
  /**
   * Opaque reference identity; the revision must be supplied separately.
   */
  id: string;
  /**
   * Exact immutable revision reference; does not resolve or follow a moving alias.
   */
  revision: string;
}
/**
 * Cumulative plan budget; retries do not reset it.
 */
export interface ExecutionBudget {
  /**
   * Maximum attempts for the whole plan; retries never multiply time/output budgets.
   */
  maxAttempts: number;
  /**
   * Aggregate stdout/stderr/result bytes across all attempts, including discarded output.
   */
  totalOutputBytes: number;
  /**
   * Total elapsed wall time from the first attempt start, including retries/backoff/waits.
   * Pre-execution approval waits are excluded; retries never replenish this budget.
   */
  totalTimeoutMs: number;
}
/**
 * Originating OS account/session reference, separate from requested run-as identity.
 */
export interface OsSessionRef {
  account: OsAccountRef;
  /**
   * Origin device reference; it does not establish registration or target authority.
   */
  device: string;
  /**
   * Origin OS login/session reference, including an explicit test reference in fixtures.
   */
  session: string;
}
/**
 * Login account at the origin; never implicitly equated to the product actor.
 */
export interface OsAccountRef {
  /**
   * OS namespace of this reference or target; does not assert platform support.
   */
  platform: "windows" | "macos" | "linux";
  /**
   * Opaque stable OS account reference, such as a SID/UID reference, not an authentication credential.
   */
  subject: string;
}
/**
 * Exact connection configuration used at initiation; no external account identity.
 */
export interface VersionedRef1 {
  /**
   * Opaque reference identity; the revision must be supplied separately.
   */
  id: string;
  /**
   * Exact immutable revision reference; does not resolve or follow a moving alias.
   */
  revision: string;
}
/**
 * Originating OS account/session reference, separate from requested run-as identity.
 */
export interface OsSessionRef1 {
  account: OsAccountRef;
  /**
   * Origin device reference; it does not establish registration or target authority.
   */
  device: string;
  /**
   * Origin OS login/session reference, including an explicit test reference in fixtures.
   */
  session: string;
}
/**
 * Exact policy revision associated with this request or audit decision.
 */
export interface VersionedRef2 {
  /**
   * Opaque reference identity; the revision must be supplied separately.
   */
  id: string;
  /**
   * Exact immutable revision reference; does not resolve or follow a moving alias.
   */
  revision: string;
}
/**
 * Exact interpreter selection.
 */
export interface InterpreterRef {
  artifact: ExactArtifactRef1;
  profile: VersionedRef3;
}
/**
 * Binary identity; the adapter must verify bytes, without PATH or version fallback.
 */
export interface ExactArtifactRef1 {
  resource: VersionedRef;
  /**
   * Expected content SHA-256. The adapter must verify the actual bytes before use.
   */
  sha256: string;
}
/**
 * Calling convention identity/revision; matched together with the binary.
 */
export interface VersionedRef3 {
  /**
   * Opaque reference identity; the revision must be supplied separately.
   */
  id: string;
  /**
   * Exact immutable revision reference; does not resolve or follow a moving alias.
   */
  revision: string;
}
/**
 * Action and exact resource revision.
 */
export interface Operation {
  /**
   * Stable operation identifier owned by the catalog/authorization policy.
   */
  action: string;
  resource: VersionedRef4;
}
/**
 * Exact resource ID and revision; no latest-version lookup is performed here.
 */
export interface VersionedRef4 {
  /**
   * Opaque reference identity; the revision must be supplied separately.
   */
  id: string;
  /**
   * Exact immutable revision reference; does not resolve or follow a moving alias.
   */
  revision: string;
}
/**
 * Exact policy revision.
 */
export interface VersionedRef5 {
  /**
   * Opaque reference identity; the revision must be supplied separately.
   */
  id: string;
  /**
   * Exact immutable revision reference; does not resolve or follow a moving alias.
   */
  revision: string;
}
/**
 * Explicit account reference; never implicitly mapped to a product actor by name or email.
 */
export interface OsAccountRef1 {
  /**
   * OS namespace of this reference or target; does not assert platform support.
   */
  platform: "windows" | "macos" | "linux";
  /**
   * Opaque stable OS account reference, such as a SID/UID reference, not an authentication credential.
   */
  subject: string;
}
/**
 * Exact account whose session is required, not inferred from the initiator.
 */
export interface OsAccountRef2 {
  /**
   * OS namespace of this reference or target; does not assert platform support.
   */
  platform: "windows" | "macos" | "linux";
  /**
   * Opaque stable OS account reference, such as a SID/UID reference, not an authentication credential.
   */
  subject: string;
}
/**
 * Explicit device/platform/user target.
 */
export interface Target {
  /**
   * Explicit device reference in the containing authority/context; not registration evidence.
   */
  device: string;
  /**
   * OS namespace of this reference or target; does not assert platform support.
   */
  platform: "windows" | "macos" | "linux";
  /**
   * Device-wide or explicit-user scope as defined by this type.
   */
  scope:
    | {
        kind: "device";
      }
    | {
        account: OsAccountRef3;
        kind: "user";
      };
}
/**
 * Explicit account reference; never implicitly mapped to a product actor by name or email.
 */
export interface OsAccountRef3 {
  /**
   * OS namespace of this reference or target; does not assert platform support.
   */
  platform: "windows" | "macos" | "linux";
  /**
   * Opaque stable OS account reference, such as a SID/UID reference, not an authentication credential.
   */
  subject: string;
}
/**
 * Original validity window.
 */
export interface ValidityWindow {
  /**
   * Exclusive validity deadline as UTC Unix milliseconds, strictly after the start.
   */
  expiresAtUnixMs: number;
  /**
   * Earliest validity instant as UTC Unix milliseconds; no system clock is consulted here.
   */
  notBeforeUnixMs: number;
}
/**
 * Authoritative lifecycle projection.
 */
export interface ExecutionStatus {
  /**
   * Latest durable, value-only admission decision, independent of prior attempt facts.
   */
  admission: AdmissionStatus | null;
  /**
   * Fixture assessment if recorded; Unknown is not success.
   */
  assessment: EffectAssessment | null;
  /**
   * Current admitted attempt, absent before admission.
   */
  attemptId: AttemptId | null;
  /**
   * Total admitted attempts; retries never reset it.
   */
  attempts: number;
  /**
   * Sticky cancellation request, independently of termination.
   */
  cancelRequested: boolean;
  /**
   * Exact frozen plan identity.
   * Canonical C01 plan digest.
   */
  contentDigest: string;
  /**
   * First-delivery diagnosis; never evidence that execution had no effect.
   */
  dispatchCause: DispatchCause | null;
  /**
   * Authorized evidence references only.
   */
  evidence: EvidenceRef[];
  /**
   * Explicit fixture provenance, also present before the first attempt.
   */
  mode: "test" | "real";
  /**
   * The initial submission receipt exists; preview alone leaves this false.
   * Original reliable business identity.
   */
  operationRequestId: string;
  /**
   * Current derived lifecycle phase.
   */
  phase:
    | "waiting"
    | "admissionDenied"
    | "approvalRequired"
    | "confirmationRequired"
    | "accepted"
    | "running"
    | "outcomeUnknown"
    | "executionEnded"
    | "verified"
    | "failedBeforeDispatch"
    | "cancelled";
  /**
   * Redacted process progress, distinct from lifecycle termination and effect proof.
   */
  process: ProcessSummary | null;
  /**
   * Safe independent software diagnostic; observed state is not final success.
   */
  software: SoftwareDiagnostic | null;
  /**
   * Last stop request response; independent of termination/effect evidence.
   */
  stopOutcome: StopOutcome | null;
}
/**
 * Versioned observation reference and runner provenance; the referenced fact remains unverified.
 *
 * This interface was referenced by `ExecutionTaskDetails`'s JSON-Schema
 * via the `definition` "EvidenceRef".
 */
export interface EvidenceRef {
  /**
   * Recorded observation category; a category label does not prove an external fact.
   */
  kind: "testResult" | "processExited" | "stateObserved";
  reference: VersionedRef6;
  /**
   * Runner reference whose evidence is being recorded, including an explicit fixture runner in tests.
   */
  runner: string;
}
/**
 * Exact versioned reference. Authenticity and access are checked by its owner.
 */
export interface VersionedRef6 {
  /**
   * Opaque reference identity; the revision must be supplied separately.
   */
  id: string;
  /**
   * Exact immutable revision reference; does not resolve or follow a moving alias.
   */
  revision: string;
}
/**
 * Ordinary result projection. No raw output, paths, process identifiers or secrets.
 *
 * This interface was referenced by `ExecutionTaskDetails`'s JSON-Schema
 * via the `definition` "ProcessSummary".
 */
export interface ProcessSummary {
  /**
   * Stop/failure classification.
   */
  end:
    | "rejected"
    | "exited"
    | "cancelled"
    | "timedOut"
    | "outputLimit"
    | "unknown";
  /**
   * Root exit code, independently from effect or scope quiescence.
   */
  exitCode: number | null;
  /**
   * First mechanism failure. Required even when no failure has occurred.
   */
  failureKind:
    | "none"
    | "denied"
    | "unbound"
    | "capability"
    | "unsupported"
    | "invalidInput"
    | "capacity"
    | "conflict"
    | "unavailable"
    | "runtime"
    | "spawn"
    | "inputDelivery"
    | "capture"
    | "supervision"
    | "outputValidation";
  /**
   * Root capture completed; not proof of all descendants terminating.
   */
  finished: boolean;
  /**
   * Capture/decoding quality, not a business success bit.
   */
  quality: "complete" | "truncated" | "failed" | "partial";
  /**
   * Explicit full-scope proof; false means unproven.
   */
  quiescent: boolean;
  /**
   * Bytes observed including discarded bytes.
   */
  totalOutputBytes: number;
}
/**
 * Resource revision and exact SHA-256 content identity; does not itself verify downloaded bytes.
 *
 * This interface was referenced by `ExecutionTaskDetails`'s JSON-Schema
 * via the `definition` "ExactArtifactRef".
 */
export interface ExactArtifactRef2 {
  resource: VersionedRef;
  /**
   * Expected content SHA-256. The adapter must verify the actual bytes before use.
   */
  sha256: string;
}
/**
 * Cumulative allowances for the entire plan, never replenished by retries.
 *
 * This interface was referenced by `ExecutionTaskDetails`'s JSON-Schema
 * via the `definition` "ExecutionBudget".
 */
export interface ExecutionBudget1 {
  /**
   * Maximum attempts for the whole plan; retries never multiply time/output budgets.
   */
  maxAttempts: number;
  /**
   * Aggregate stdout/stderr/result bytes across all attempts, including discarded output.
   */
  totalOutputBytes: number;
  /**
   * Total elapsed wall time from the first attempt start, including retries/backoff/waits.
   * Pre-execution approval waits are excluded; retries never replenish this budget.
   */
  totalTimeoutMs: number;
}
/**
 * Authorized value-only task projection. Never includes launch, parameters or raw output.
 *
 * This interface was referenced by `ExecutionTaskDetails`'s JSON-Schema
 * via the `definition` "ExecutionStatus".
 */
export interface ExecutionStatus1 {
  /**
   * Latest durable, value-only admission decision, independent of prior attempt facts.
   */
  admission: AdmissionStatus | null;
  /**
   * Fixture assessment if recorded; Unknown is not success.
   */
  assessment: EffectAssessment | null;
  /**
   * Current admitted attempt, absent before admission.
   */
  attemptId: AttemptId | null;
  /**
   * Total admitted attempts; retries never reset it.
   */
  attempts: number;
  /**
   * Sticky cancellation request, independently of termination.
   */
  cancelRequested: boolean;
  /**
   * Exact frozen plan identity.
   * Canonical C01 plan digest.
   */
  contentDigest: string;
  /**
   * First-delivery diagnosis; never evidence that execution had no effect.
   */
  dispatchCause: DispatchCause | null;
  /**
   * Authorized evidence references only.
   */
  evidence: EvidenceRef[];
  /**
   * Explicit fixture provenance, also present before the first attempt.
   */
  mode: "test" | "real";
  /**
   * The initial submission receipt exists; preview alone leaves this false.
   * Original reliable business identity.
   */
  operationRequestId: string;
  /**
   * Current derived lifecycle phase.
   */
  phase:
    | "waiting"
    | "admissionDenied"
    | "approvalRequired"
    | "confirmationRequired"
    | "accepted"
    | "running"
    | "outcomeUnknown"
    | "executionEnded"
    | "verified"
    | "failedBeforeDispatch"
    | "cancelled";
  /**
   * Redacted process progress, distinct from lifecycle termination and effect proof.
   */
  process: ProcessSummary | null;
  /**
   * Safe independent software diagnostic; observed state is not final success.
   */
  software: SoftwareDiagnostic | null;
  /**
   * Last stop request response; independent of termination/effect evidence.
   */
  stopOutcome: StopOutcome | null;
}
/**
 * Allowlisted view of the immutable plan; no parameters, launch inputs, secrets or audit.
 *
 * This interface was referenced by `ExecutionTaskDetails`'s JSON-Schema
 * via the `definition` "FrozenExecutionSummary".
 */
export interface FrozenExecutionSummary1 {
  /**
   * Restrictions summarized without individual private values.
   */
  access:
    | {
        kind: "osIdentity";
      }
    | {
        /**
         * Required child process allowance.
         */
        allowChildProcesses: boolean;
        kind: "restricted";
        /**
         * Whether networking is completely denied.
         */
        networkDenied: boolean;
        /**
         * Number of exact allowlisted destinations; never their values.
         */
        networkDestinationCount: number;
        /**
         * Number of declared read paths.
         */
        readPathCount: number;
        /**
         * Required isolation; this is not an observation that enforcement succeeded.
         */
        requireSandbox: boolean;
        /**
         * Number of declared write paths.
         */
        writePathCount: number;
      };
  /**
   * Permission-bearing principal; not the model account.
   */
  actor: string;
  artifact: ExactArtifactRef;
  /**
   * Product authority bound to the exact plan.
   */
  authority:
    | {
        /**
         * Authority reference in this variant namespace; no proof of issuer authenticity.
         */
        id: string;
        kind: "local";
      }
    | {
        /**
         * Authority reference in this variant namespace; no proof of issuer authenticity.
         */
        id: string;
        kind: "enterprise";
        /**
         * Explicit enterprise tenant reference; local/test authority never fabricates a tenant.
         */
        tenant: string;
      }
    | {
        /**
         * Authority reference in this variant namespace; no proof of issuer authenticity.
         */
        id: string;
        kind: "test";
      };
  budget: ExecutionBudget;
  /**
   * Digest covers the complete original plan, including omitted private values.
   */
  contentDigest: string;
  /**
   * Closed execution kind without private software paths or source inputs.
   */
  execution:
    | {
        kind: "process";
      }
    | {
        /**
         * Selected platform adapter.
         */
        adapter:
          | "msi"
          | "winget"
          | "pkg"
          | "homebrew"
          | "windowsBundle"
          | "macosBundle";
        kind: "software";
        /**
         * Selected mutation.
         */
        mutation: "install" | "upgrade" | "downgrade" | "uninstall";
      };
  /**
   * Human or AI origin, without granting execution permission.
   */
  initiator:
    | {
        kind: "human";
        osSession: OsSessionRef;
      }
    | {
        config: VersionedRef1;
        /**
         * Originating AI conversation reference in the provider namespace.
         */
        conversation: string;
        kind: "ai";
        osSession: OsSessionRef1;
        /**
         * Provider namespace, independent of product authentication.
         */
        provider: string;
        /**
         * Originating tool-call reference; cannot act as a product approval.
         */
        toolCall: string;
      }
    | {
        kind: "policy";
        policy: VersionedRef2;
      };
  interpreter: InterpreterRef;
  operation: Operation;
  policy: VersionedRef5;
  /**
   * Exact frozen plan identity.
   */
  requestId: string;
  /**
   * Explicit execution identity; never inferred from a provider login.
   */
  runAs:
    | {
        account: OsAccountRef1;
        kind: "user";
      }
    | {
        kind: "system";
        /**
         * OS namespace of this reference or target; does not assert platform support.
         */
        platform: "windows" | "macos" | "linux";
      };
  /**
   * Version of the frozen execution plan, independent of the AI wire version.
   */
  schemaVersion: 4;
  /**
   * Required target user session.
   */
  sessionRequirement:
    | {
        kind: "notRequired";
      }
    | {
        account: OsAccountRef2;
        kind: "activeUser";
      };
  target: Target;
  validity: ValidityWindow;
}
/**
 * Exact binary and immutable calling convention. Neither reference proves availability.
 *
 * This interface was referenced by `ExecutionTaskDetails`'s JSON-Schema
 * via the `definition` "InterpreterRef".
 */
export interface InterpreterRef1 {
  artifact: ExactArtifactRef1;
  profile: VersionedRef3;
}
/**
 * Action and exact resource identity submitted to the authorization owner.
 *
 * This interface was referenced by `ExecutionTaskDetails`'s JSON-Schema
 * via the `definition` "Operation".
 */
export interface Operation1 {
  /**
   * Stable operation identifier owned by the catalog/authorization policy.
   */
  action: string;
  resource: VersionedRef4;
}
/**
 * Opaque account reference in an OS namespace, independent of product or provider identity.
 *
 * This interface was referenced by `ExecutionTaskDetails`'s JSON-Schema
 * via the `definition` "OsAccountRef".
 */
export interface OsAccountRef4 {
  /**
   * OS namespace of this reference or target; does not assert platform support.
   */
  platform: "windows" | "macos" | "linux";
  /**
   * Opaque stable OS account reference, such as a SID/UID reference, not an authentication credential.
   */
  subject: string;
}
/**
 * Claimed OS login provenance at the request origin, separate from target and run-as identity.
 *
 * This interface was referenced by `ExecutionTaskDetails`'s JSON-Schema
 * via the `definition` "OsSessionRef".
 */
export interface OsSessionRef2 {
  account: OsAccountRef;
  /**
   * Origin device reference; it does not establish registration or target authority.
   */
  device: string;
  /**
   * Origin OS login/session reference, including an explicit test reference in fixtures.
   */
  session: string;
}
/**
 * Explicit device, platform and scope bound into the plan digest.
 *
 * This interface was referenced by `ExecutionTaskDetails`'s JSON-Schema
 * via the `definition` "Target".
 */
export interface Target1 {
  /**
   * Explicit device reference in the containing authority/context; not registration evidence.
   */
  device: string;
  /**
   * OS namespace of this reference or target; does not assert platform support.
   */
  platform: "windows" | "macos" | "linux";
  /**
   * Device-wide or explicit-user scope as defined by this type.
   */
  scope:
    | {
        kind: "device";
      }
    | {
        account: OsAccountRef3;
        kind: "user";
      };
}
/**
 * UTC Unix milliseconds. The host separately validates current time and revocation freshness.
 *
 * This interface was referenced by `ExecutionTaskDetails`'s JSON-Schema
 * via the `definition` "ValidityWindow".
 */
export interface ValidityWindow1 {
  /**
   * Exclusive validity deadline as UTC Unix milliseconds, strictly after the start.
   */
  expiresAtUnixMs: number;
  /**
   * Earliest validity instant as UTC Unix milliseconds; no system clock is consulted here.
   */
  notBeforeUnixMs: number;
}
/**
 * Exact resource/configuration reference. Resolution and authenticity belong to the owner.
 *
 * This interface was referenced by `ExecutionTaskDetails`'s JSON-Schema
 * via the `definition` "VersionedRef".
 */
export interface VersionedRef7 {
  /**
   * Opaque reference identity; the revision must be supplied separately.
   */
  id: string;
  /**
   * Exact immutable revision reference; does not resolve or follow a moving alias.
   */
  revision: string;
}
