// Generated by scripts/check-execution-bindings.mjs --write; edit Rust owners instead.

/**
 * Untrusted proposal input; there is no approval, actor or permission field.
 */
export type ExecuteInput =
  | {
      catalog: {
        selection: CatalogInput;
      };
    }
  | {
      script: {
        interpreter: ExactArtifactRef;
        /**
         * Stable operation identity.
         */
        operationRequestId: string;
        /**
         * Original UTF-8 script, never executed or echoed.
         */
        sourceUtf8: string;
      };
    };

/**
 * Exact selection.
 */
export interface CatalogInput {
  /**
   * Original parameter object; schema/rules are obtained from execution_catalog.
   */
  arguments: {
    [k: string]: unknown;
  };
  catalog: CatalogRef;
  /**
   * Catalog item ID.
   */
  itemId: string;
  /**
   * Stable business identity, independent of the MCP request ID.
   */
  operationRequestId: string;
  /**
   * Operation variant ID.
   */
  variantId: string;
}
/**
 * Exact catalog identity and digest.
 */
export interface CatalogRef {
  /**
   * Complete namespace including enterprise tenant when applicable.
   */
  authority:
    | {
        /**
         * Authority reference in this variant namespace; no proof of issuer authenticity.
         */
        id: string;
        kind: "local";
      }
    | {
        /**
         * Authority reference in this variant namespace; no proof of issuer authenticity.
         */
        id: string;
        kind: "enterprise";
        /**
         * Explicit enterprise tenant reference; local/test authority never fabricates a tenant.
         */
        tenant: string;
      }
    | {
        /**
         * Authority reference in this variant namespace; no proof of issuer authenticity.
         */
        id: string;
        kind: "test";
      };
  /**
   * Computed canonical catalog SHA-256.
   */
  digest: string;
  identity: VersionedRef;
}
/**
 * Catalog ID/revision, not resource version or format version.
 */
export interface VersionedRef {
  /**
   * Opaque reference identity; the revision must be supplied separately.
   */
  id: string;
  /**
   * Exact immutable revision reference; does not resolve or follow a moving alias.
   */
  revision: string;
}
/**
 * Explicit interpreter identity, subject to service validation.
 */
export interface ExactArtifactRef {
  resource: VersionedRef1;
  /**
   * Expected content SHA-256. The adapter must verify the actual bytes before use.
   */
  sha256: string;
}
/**
 * Exact resource ID and revision; no latest-version lookup is performed here.
 */
export interface VersionedRef1 {
  /**
   * Opaque reference identity; the revision must be supplied separately.
   */
  id: string;
  /**
   * Exact immutable revision reference; does not resolve or follow a moving alias.
   */
  revision: string;
}
