// Generated by scripts/check-execution-bindings.mjs --write; edit Rust owners instead.

/**
 * A selection references exact backend content and carries no script or local catalog model.
 */
export interface BackendSelection {
  /**
   * Original backend attempt.
   */
  attempt: string;
  /**
   * Original request shown with the offer, used unchanged for recovery.
   */
  request: string;
  /**
   * Revision shown to the user/model.
   */
  revision: string;
  /**
   * Backend task identity.
   */
  task: string;
}
