// Generated by scripts/check-execution-bindings.mjs --write; edit Rust owners instead.

/**
 * Authorized lookup/cancellation within the host-bound namespace.
 */
export interface OperationRequest {
  /**
   * Business identity, never inferred from a JSON-RPC ID.
   */
  operationRequestId: string;
}
