// Generated by scripts/check-execution-bindings.mjs --write; edit Rust owners instead.

/**
 * Query result spanning preparation and actual execution without inventing a frozen plan.
 */
export type BackendTaskView =
  | {
      kind: "pending";
      value: BackendRequest;
    }
  | {
      kind: "execution";
      value: ExecutionTaskDetails;
    };
/**
 * Closed preparation diagnosis without backend bodies or local paths.
 */
export type BackendRequestFailure =
  | "preparationFailed"
  | "interrupted"
  | "expired"
  | "revoked";
/**
 * Safe native package effect for task details.
 */
export type SoftwareDeploymentSummary = "targetUser" | "futureUsers";
/**
 * Value-only admission result; policy/rule/approver details remain in privileged audit.
 */
export type AdmissionStatus = "admitted" | "denied" | "approvalRequired";
/**
 * Verified assessment of the whole controlled attempt, not text from tool output.
 */
export type EffectAssessment =
  | "noEffect"
  | "satisfied"
  | "notSatisfied"
  | "unknown";
/**
 * Execution attempt correlation identity.
 */
export type AttemptId = string;
/**
 * Closed first-delivery diagnostics. These are not observations of termination or effects.
 */
export type DispatchCause =
  | "capabilityUnavailable"
  | "clockUnavailable"
  | "cancelled"
  | {
      limit: LimitReason;
    }
  | "staleRevision"
  | "runnerMismatch"
  | "configurationUnavailable"
  | "authorityUnavailable"
  | "lifecycleChanged"
  | "runnerRejected"
  | "deliveryUnknown"
  | "runnerError";
/**
 * Explicit reason a validity or cumulative budget bound prevents work.
 */
export type LimitReason =
  | "notYetValid"
  | "expired"
  | "timeout"
  | "output"
  | "attempts";
/**
 * Safe software diagnostic; contains no paths, source coordinates or captured output.
 */
export type SoftwareDiagnostic =
  | "awaitingDetection"
  | "restartPending"
  | "detectionUnavailable"
  | "unrecognizedVersion"
  | "detectionBudgetExceeded"
  | "desiredStateObserved"
  | "desiredStateMissing"
  | "cleanupPending"
  | "cleanupUnverified";
/**
 * Closed stop request diagnostics. Neither variant is a termination/effect observation.
 */
export type StopOutcome = "acknowledged" | "failed";

/**
 * Original offer, caller binding and durable preparation state.
 */
export interface BackendRequest {
  /**
   * Diagnosis when preparation failed.
   */
  failure: BackendRequestFailure | null;
  offer: BackendTask;
  /**
   * Monotonic journal revision.
   */
  revision: number;
  /**
   * Preparation state, separate from execution lifecycle.
   */
  state: "proposed" | "selected" | "submitting" | "failed" | "cancelled";
  /**
   * OS-authenticated original trigger; never accepted from an IPC request body.
   */
  trigger:
    | {
        kind: "automatic";
      }
    | {
        kind: "human";
        osSession: OsSessionRef;
      }
    | {
        config: VersionedRef;
        /**
         * Conversation reference used for audit correlation.
         */
        conversation: string;
        kind: "ai";
        osSession: OsSessionRef1;
        /**
         * Tool request reference used for audit correlation.
         */
        toolCall: string;
      };
}
/**
 * Exact offer and its display summary.
 */
export interface BackendTask {
  /**
   * Backend attempt identity; reconnect never allocates a new attempt.
   */
  attempt: string;
  /**
   * Exclusive UTC Unix expiry in seconds.
   */
  expiresAt: number;
  /**
   * Deterministic original execution request used for status after response loss.
   */
  request: string;
  /**
   * Full signed offer revision.
   */
  revision: string;
  /**
   * Complete safe action preview, immutable with the offer revision.
   */
  summary:
    | {
        /**
         * Account class selected by the backend.
         */
        identity: "system" | "user";
        kind: "script";
      }
    | {
        /**
         * Install, uninstall or detection intent.
         */
        intent: "install" | "detect" | "uninstall";
        kind: "software";
        /**
         * Ordered prerequisites and final package.
         */
        steps: BackendStepSummary[];
      };
  /**
   * Backend task identity.
   */
  task: string;
  /**
   * Safe display text selected by the backend.
   */
  title: string;
  /**
   * Requires an explicit local user action before requesting Start.
   */
  userInitiated: boolean;
}
/**
 * Exact software coordinate displayed before user confirmation.
 */
export interface BackendStepSummary {
  /**
   * Execution account class.
   */
  identity: "system" | "user";
  /**
   * Exact package selected by the backend.
   */
  package: string;
  /**
   * Exact version; no implicit latest.
   */
  version: string;
}
/**
 * Actual native account and login session, supplied by ingress.
 */
export interface OsSessionRef {
  account: OsAccountRef;
  /**
   * Origin device reference; it does not establish registration or target authority.
   */
  device: string;
  /**
   * Origin OS login/session reference, including an explicit test reference in fixtures.
   */
  session: string;
}
/**
 * Login account at the origin; never implicitly equated to the product actor.
 */
export interface OsAccountRef {
  /**
   * OS namespace of this reference or target; does not assert platform support.
   */
  platform: "windows" | "macos" | "linux";
  /**
   * Opaque stable OS account reference, such as a SID/UID reference, not an authentication credential.
   */
  subject: string;
}
/**
 * Native AI connection configuration, not a provider identity grant.
 */
export interface VersionedRef {
  /**
   * Opaque reference identity; the revision must be supplied separately.
   */
  id: string;
  /**
   * Exact immutable revision reference; does not resolve or follow a moving alias.
   */
  revision: string;
}
/**
 * Actual native account and login session, supplied by ingress.
 */
export interface OsSessionRef1 {
  account: OsAccountRef;
  /**
   * Origin device reference; it does not establish registration or target authority.
   */
  device: string;
  /**
   * Origin OS login/session reference, including an explicit test reference in fixtures.
   */
  session: string;
}
/**
 * Real frozen input projection and lifecycle facts.
 */
export interface ExecutionTaskDetails {
  action: FrozenExecutionSummary;
  status: ExecutionStatus;
}
/**
 * Redacted frozen plan bound to that lifecycle.
 */
export interface FrozenExecutionSummary {
  /**
   * Restrictions summarized without individual private values.
   */
  access:
    | {
        kind: "osIdentity";
      }
    | {
        /**
         * Required child process allowance.
         */
        allowChildProcesses: boolean;
        kind: "restricted";
        /**
         * Whether networking is completely denied.
         */
        networkDenied: boolean;
        /**
         * Number of exact allowlisted destinations; never their values.
         */
        networkDestinationCount: number;
        /**
         * Number of declared read paths.
         */
        readPathCount: number;
        /**
         * Required isolation; this is not an observation that enforcement succeeded.
         */
        requireSandbox: boolean;
        /**
         * Number of declared write paths.
         */
        writePathCount: number;
      };
  /**
   * Permission-bearing principal; not the model account.
   */
  actor: string;
  artifact: ExactArtifactRef;
  /**
   * Product authority bound to the exact plan.
   */
  authority:
    | {
        /**
         * Authority reference in this variant namespace; no proof of issuer authenticity.
         */
        id: string;
        kind: "local";
      }
    | {
        /**
         * Authority reference in this variant namespace; no proof of issuer authenticity.
         */
        id: string;
        kind: "enterprise";
        /**
         * Explicit enterprise tenant reference; local/test authority never fabricates a tenant.
         */
        tenant: string;
      }
    | {
        /**
         * Authority reference in this variant namespace; no proof of issuer authenticity.
         */
        id: string;
        kind: "test";
      };
  budget: ExecutionBudget;
  /**
   * Digest covers the complete original plan, including omitted private values.
   */
  contentDigest: string;
  /**
   * Closed execution kind without private software paths or source inputs.
   */
  execution:
    | {
        /**
         * Fixed backend operation.
         */
        intent: "install" | "detect" | "uninstall";
        kind: "softwareProgram";
        /**
         * Safe step identities, without launch inputs or paths.
         */
        steps: SoftwareStepSummary[];
      }
    | {
        kind: "process";
      };
  /**
   * Human or AI origin, without granting execution permission.
   */
  initiator:
    | {
        /**
         * Exact server execution attempt.
         */
        attempt: string;
        kind: "backend";
        /**
         * Exact server task, independently verified by the host.
         */
        task: string;
        /**
         * Authenticated local trigger or automatic backend dispatch.
         */
        trigger:
          | {
              kind: "automatic";
            }
          | {
              kind: "human";
              osSession: OsSessionRef;
            }
          | {
              config: VersionedRef;
              /**
               * Conversation reference used for audit correlation.
               */
              conversation: string;
              kind: "ai";
              osSession: OsSessionRef1;
              /**
               * Tool request reference used for audit correlation.
               */
              toolCall: string;
            };
      }
    | {
        kind: "human";
        osSession: OsSessionRef2;
      }
    | {
        config: VersionedRef2;
        /**
         * Originating AI conversation reference in the provider namespace.
         */
        conversation: string;
        kind: "ai";
        osSession: OsSessionRef3;
        /**
         * Provider namespace, independent of product authentication.
         */
        provider: string;
        /**
         * Originating tool-call reference; cannot act as a product approval.
         */
        toolCall: string;
      }
    | {
        kind: "policy";
        policy: VersionedRef3;
      };
  interpreter: InterpreterRef;
  operation: Operation;
  policy: VersionedRef6;
  /**
   * Exact frozen plan identity.
   */
  requestId: string;
  /**
   * Explicit execution identity; never inferred from a provider login.
   */
  runAs:
    | {
        account: OsAccountRef1;
        kind: "user";
      }
    | {
        kind: "system";
        /**
         * OS namespace of this reference or target; does not assert platform support.
         */
        platform: "windows" | "macos" | "linux";
      };
  /**
   * Version of the frozen execution plan, independent of the AI wire version.
   */
  schemaVersion: 6;
  /**
   * Required target user session.
   */
  sessionRequirement:
    | {
        kind: "notRequired";
      }
    | {
        account: OsAccountRef2;
        kind: "activeUser";
        /**
         * Exact native login session; a new login for the same account is not interchangeable.
         */
        session: string;
      };
  target: Target;
  validity: ValidityWindow;
}
/**
 * Exact artifact revision and content hash.
 */
export interface ExactArtifactRef {
  resource: VersionedRef1;
  /**
   * Expected content SHA-256. The adapter must verify the actual bytes before use.
   */
  sha256: string;
}
/**
 * Exact resource ID and revision; no latest-version lookup is performed here.
 */
export interface VersionedRef1 {
  /**
   * Opaque reference identity; the revision must be supplied separately.
   */
  id: string;
  /**
   * Exact immutable revision reference; does not resolve or follow a moving alias.
   */
  revision: string;
}
/**
 * Cumulative plan budget; retries do not reset it.
 */
export interface ExecutionBudget {
  /**
   * Maximum attempts for the whole plan; retries never multiply time/output budgets.
   */
  maxAttempts: number;
  /**
   * Aggregate stdout/stderr/result bytes across all attempts, including discarded output.
   */
  totalOutputBytes: number;
  /**
   * Total elapsed wall time from the first attempt start, including retries/backoff/waits.
   * Pre-execution approval waits are excluded; retries never replenish this budget.
   */
  totalTimeoutMs: number;
}
/**
 * Safe software-step projection from the frozen program.
 */
export interface SoftwareStepSummary {
  /**
   * Selected closed adapter.
   */
  adapter:
    | "msi"
    | "exe"
    | "msix"
    | "dmgApp"
    | "dmgPkg"
    | "winget"
    | "pkg"
    | "homebrew"
    | "windowsBundle"
    | "macosBundle";
  /**
   * Native MSIX effect, separately from OS account used to execute it.
   */
  deployment: SoftwareDeploymentSummary | null;
  /**
   * Exact backend package.
   */
  package: string;
  /**
   * Actual execution identity for the step.
   */
  runAs:
    | {
        account: OsAccountRef1;
        kind: "user";
      }
    | {
        kind: "system";
        /**
         * OS namespace of this reference or target; does not assert platform support.
         */
        platform: "windows" | "macos" | "linux";
      };
  /**
   * Fixed package version.
   */
  version: string;
}
/**
 * Explicit account reference; never implicitly mapped to a product actor by name or email.
 */
export interface OsAccountRef1 {
  /**
   * OS namespace of this reference or target; does not assert platform support.
   */
  platform: "windows" | "macos" | "linux";
  /**
   * Opaque stable OS account reference, such as a SID/UID reference, not an authentication credential.
   */
  subject: string;
}
/**
 * Originating OS account/session reference, separate from requested run-as identity.
 */
export interface OsSessionRef2 {
  account: OsAccountRef;
  /**
   * Origin device reference; it does not establish registration or target authority.
   */
  device: string;
  /**
   * Origin OS login/session reference, including an explicit test reference in fixtures.
   */
  session: string;
}
/**
 * Exact connection configuration used at initiation; no external account identity.
 */
export interface VersionedRef2 {
  /**
   * Opaque reference identity; the revision must be supplied separately.
   */
  id: string;
  /**
   * Exact immutable revision reference; does not resolve or follow a moving alias.
   */
  revision: string;
}
/**
 * Originating OS account/session reference, separate from requested run-as identity.
 */
export interface OsSessionRef3 {
  account: OsAccountRef;
  /**
   * Origin device reference; it does not establish registration or target authority.
   */
  device: string;
  /**
   * Origin OS login/session reference, including an explicit test reference in fixtures.
   */
  session: string;
}
/**
 * Exact policy revision associated with this request or audit decision.
 */
export interface VersionedRef3 {
  /**
   * Opaque reference identity; the revision must be supplied separately.
   */
  id: string;
  /**
   * Exact immutable revision reference; does not resolve or follow a moving alias.
   */
  revision: string;
}
/**
 * Exact interpreter selection.
 */
export interface InterpreterRef {
  artifact: ExactArtifactRef1;
  profile: VersionedRef4;
}
/**
 * Binary identity; the adapter must verify bytes, without PATH or version fallback.
 */
export interface ExactArtifactRef1 {
  resource: VersionedRef1;
  /**
   * Expected content SHA-256. The adapter must verify the actual bytes before use.
   */
  sha256: string;
}
/**
 * Calling convention identity/revision; matched together with the binary.
 */
export interface VersionedRef4 {
  /**
   * Opaque reference identity; the revision must be supplied separately.
   */
  id: string;
  /**
   * Exact immutable revision reference; does not resolve or follow a moving alias.
   */
  revision: string;
}
/**
 * Action and exact resource revision.
 */
export interface Operation {
  /**
   * Stable operation identifier owned by the catalog/authorization policy.
   */
  action: string;
  resource: VersionedRef5;
}
/**
 * Exact resource ID and revision; no latest-version lookup is performed here.
 */
export interface VersionedRef5 {
  /**
   * Opaque reference identity; the revision must be supplied separately.
   */
  id: string;
  /**
   * Exact immutable revision reference; does not resolve or follow a moving alias.
   */
  revision: string;
}
/**
 * Exact policy revision.
 */
export interface VersionedRef6 {
  /**
   * Opaque reference identity; the revision must be supplied separately.
   */
  id: string;
  /**
   * Exact immutable revision reference; does not resolve or follow a moving alias.
   */
  revision: string;
}
/**
 * Exact account whose session is required, not inferred from the initiator.
 */
export interface OsAccountRef2 {
  /**
   * OS namespace of this reference or target; does not assert platform support.
   */
  platform: "windows" | "macos" | "linux";
  /**
   * Opaque stable OS account reference, such as a SID/UID reference, not an authentication credential.
   */
  subject: string;
}
/**
 * Explicit device/platform/user target.
 */
export interface Target {
  /**
   * Explicit device reference in the containing authority/context; not registration evidence.
   */
  device: string;
  /**
   * OS namespace of this reference or target; does not assert platform support.
   */
  platform: "windows" | "macos" | "linux";
  /**
   * Device-wide or explicit-user scope as defined by this type.
   */
  scope:
    | {
        kind: "device";
      }
    | {
        account: OsAccountRef3;
        kind: "user";
      };
}
/**
 * Explicit account reference; never implicitly mapped to a product actor by name or email.
 */
export interface OsAccountRef3 {
  /**
   * OS namespace of this reference or target; does not assert platform support.
   */
  platform: "windows" | "macos" | "linux";
  /**
   * Opaque stable OS account reference, such as a SID/UID reference, not an authentication credential.
   */
  subject: string;
}
/**
 * Original validity window.
 */
export interface ValidityWindow {
  /**
   * Exclusive validity deadline as UTC Unix milliseconds, strictly after the start.
   */
  expiresAtUnixMs: number;
  /**
   * Earliest validity instant as UTC Unix milliseconds; no system clock is consulted here.
   */
  notBeforeUnixMs: number;
}
/**
 * Authoritative lifecycle projection.
 */
export interface ExecutionStatus {
  /**
   * Latest durable, value-only admission decision, independent of prior attempt facts.
   */
  admission: AdmissionStatus | null;
  /**
   * Fixture assessment if recorded; Unknown is not success.
   */
  assessment: EffectAssessment | null;
  /**
   * Current admitted attempt, absent before admission.
   */
  attemptId: AttemptId | null;
  /**
   * Total admitted attempts; retries never reset it.
   */
  attempts: number;
  /**
   * Sticky cancellation request, independently of termination.
   */
  cancelRequested: boolean;
  /**
   * Canonical digest of the complete immutable execution input.
   */
  contentDigest: string;
  /**
   * First-delivery diagnosis; never evidence that execution had no effect.
   */
  dispatchCause: DispatchCause | null;
  /**
   * Authorized evidence references only.
   */
  evidence: EvidenceRef[];
  /**
   * Explicit fixture provenance, also present before the first attempt.
   */
  mode: "test" | "real";
  /**
   * Original reliable business identity.
   */
  operationRequestId: string;
  /**
   * Current derived lifecycle phase.
   */
  phase:
    | "waiting"
    | "admissionDenied"
    | "approvalRequired"
    | "confirmationRequired"
    | "accepted"
    | "running"
    | "outcomeUnknown"
    | "executionEnded"
    | "verified"
    | "failedBeforeDispatch"
    | "cancelled";
  /**
   * Redacted process progress, distinct from lifecycle termination and effect proof.
   */
  process: ProcessSummary | null;
  /**
   * Safe independent software diagnostic; observed state is not final success.
   */
  software: SoftwareDiagnostic | null;
  /**
   * Last stop request response; independent of termination/effect evidence.
   */
  stopOutcome: StopOutcome | null;
}
/**
 * Versioned observation reference and runner provenance; the referenced fact remains unverified.
 */
export interface EvidenceRef {
  /**
   * Recorded observation category; a category label does not prove an external fact.
   */
  kind: "testResult" | "processExited" | "stateObserved";
  reference: VersionedRef7;
  /**
   * Runner reference whose evidence is being recorded, including an explicit fixture runner in tests.
   */
  runner: string;
}
/**
 * Exact versioned reference. Authenticity and access are checked by its owner.
 */
export interface VersionedRef7 {
  /**
   * Opaque reference identity; the revision must be supplied separately.
   */
  id: string;
  /**
   * Exact immutable revision reference; does not resolve or follow a moving alias.
   */
  revision: string;
}
/**
 * Ordinary result projection. No raw output, paths, process identifiers or secrets.
 */
export interface ProcessSummary {
  /**
   * Stop/failure classification.
   */
  end:
    | "rejected"
    | "exited"
    | "cancelled"
    | "timedOut"
    | "outputLimit"
    | "unknown";
  /**
   * Root exit code, independently from effect or scope quiescence.
   */
  exitCode: number | null;
  /**
   * First mechanism failure. Required even when no failure has occurred.
   */
  failureKind:
    | "none"
    | "denied"
    | "unbound"
    | "capability"
    | "unsupported"
    | "invalidInput"
    | "capacity"
    | "conflict"
    | "unavailable"
    | "runtime"
    | "spawn"
    | "inputDelivery"
    | "capture"
    | "supervision"
    | "outputValidation";
  /**
   * Root capture completed; not proof of all descendants terminating.
   */
  finished: boolean;
  /**
   * Capture/decoding quality, not a business success bit.
   */
  quality: "complete" | "truncated" | "failed" | "partial";
  /**
   * Explicit full-scope proof; false means unproven.
   */
  quiescent: boolean;
  /**
   * Bytes observed including discarded bytes.
   */
  totalOutputBytes: number;
}
