[package]
name = "rss-mdm-desktop"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[build-dependencies]
tauri-build.workspace = true

[dependencies]
tauri.workspace = true

[features]
default = ["custom-protocol"]
custom-protocol = ["tauri/custom-protocol"]
