[package]
name = "rss-mdm-desktop"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[build-dependencies]
tauri-build.workspace = true

[dependencies]
tauri.workspace = true
serde.workspace = true
serde_json = { workspace = true, features = ["raw_value"] }
sha2.workspace = true
service-catalog = { path = "../../../crates/service-catalog" }
execution-contract = { path = "../../../crates/execution-contract" }
execution-interaction = { path = "../../../crates/execution-interaction" }

[features]
default = ["custom-protocol"]
custom-protocol = ["tauri/custom-protocol"]

[dev-dependencies]
tauri = { workspace = true, features = ["test"] }
