// Generated by scripts/check-self-service.mjs --write; Rust owns these fixtures.
import type { Snapshot } from "./types";
const snapshot: Snapshot = {
  mode: "s1",
  instanceId: "s1-desktop-test-actor-device-r1",
  targetLabel: "macOS arm64 · 测试设备 fixture-device · 测试用户 fixture-user",
  catalog: [
    {
      riskLevel: 3,
      catalog: {
        authority: {
          kind: "test",
          id: "desktop-fixture",
        },
        identity: {
          id: "self-service",
          revision: "r1",
        },
        digest:
          "7a763c58eb07f82dd2f09db5ac7a2926c6ffa2262972c5a519b29414bcb565f3",
      },
      itemId: "blocked",
      variantId: "test",
      kind: "software",
      name: "受限软件",
      description: "固定权限拒绝样本，无法申请或提交。",
      category: "软件",
      resource: {
        reference: {
          id: "fixture-blocked",
          revision: "r1",
        },
        versionDigest:
          "96c70d18ed44a6ab1dd066c4ea7039219ed4ffea2367870ed8b4518529662e44",
        selector: {
          platform: "macos",
          architecture: "aarch64",
          key: "fixture",
        },
      },
      fields: {},
      inputSchema: {
        $schema: "https://json-schema.org/draft/2020-12/schema",
        additionalProperties: false,
        properties: {},
        required: [],
        type: "object",
      },
      display: {
        visibility: "allowed",
        requestability: "allowed",
        executability: "blocked",
      },
      reason: "S1 测试目录；最终裁决由提交时 Rust 校验产生",
      availability: "listed",
    },
    {
      riskLevel: 1,
      catalog: {
        authority: {
          kind: "test",
          id: "desktop-fixture",
        },
        identity: {
          id: "self-service",
          revision: "r1",
        },
        digest:
          "7a763c58eb07f82dd2f09db5ac7a2926c6ffa2262972c5a519b29414bcb565f3",
      },
      itemId: "diagnostics",
      variantId: "test",
      kind: "tool",
      name: "网络诊断",
      description: "只读测试动作；不会发送网络请求。",
      category: "工具",
      resource: {
        reference: {
          id: "fixture-diagnostics",
          revision: "r1",
        },
        versionDigest:
          "eac22f39e822b9b78301322d2784b71306b769d92ce84a4bce291c2d9357b5b5",
        selector: {
          platform: "macos",
          architecture: "aarch64",
          key: "fixture",
        },
      },
      fields: {
        count: {
          title: "采样次数",
          description: "留空使用目录默认值",
          required: false,
          rule: {
            type: "integer",
            minimum: 1,
            maximum: 5,
            choices: null,
            default: 3,
          },
        },
        credential: {
          title: "测试凭据引用",
          description: "仅填写引用 ID 和版本，不输入密码正文",
          required: false,
          rule: {
            type: "secretReference",
          },
        },
        detail: {
          title: "包含详细信息",
          description: "仅模拟诊断说明",
          required: false,
          rule: {
            type: "boolean",
            default: false,
          },
        },
        host: {
          title: "诊断目标",
          description: "纯测试文本，不发起网络连接",
          required: true,
          rule: {
            type: "string",
            minLength: 3,
            maxLength: 100,
            choices: null,
            default: null,
          },
        },
      },
      inputSchema: {
        $schema: "https://json-schema.org/draft/2020-12/schema",
        additionalProperties: false,
        properties: {
          count: {
            default: 3,
            description: "留空使用目录默认值",
            maximum: 5,
            minimum: 1,
            title: "采样次数",
            type: "integer",
          },
          credential: {
            $schema: "https://json-schema.org/draft/2020-12/schema",
            additionalProperties: false,
            description: "仅填写引用 ID 和版本，不输入密码正文",
            properties: {
              id: {
                description:
                  "Opaque reference identity; the revision must be supplied separately.",
                maxLength: 128,
                minLength: 1,
                pattern: "^[A-Za-z0-9][A-Za-z0-9._:/-]*$",
                type: "string",
              },
              revision: {
                description:
                  "Exact immutable revision reference; does not resolve or follow a moving alias.",
                maxLength: 128,
                minLength: 1,
                pattern: "^[A-Za-z0-9][A-Za-z0-9._:/-]*$",
                type: "string",
              },
            },
            required: ["id", "revision"],
            title: "测试凭据引用",
            type: "object",
            writeOnly: true,
          },
          detail: {
            default: false,
            description: "仅模拟诊断说明",
            title: "包含详细信息",
            type: "boolean",
          },
          host: {
            description: "纯测试文本，不发起网络连接",
            maxLength: 100,
            minLength: 3,
            title: "诊断目标",
            type: "string",
          },
        },
        required: ["host"],
        type: "object",
      },
      display: {
        visibility: "allowed",
        requestability: "allowed",
        executability: "unknown",
      },
      reason: "S1 测试目录；最终裁决由提交时 Rust 校验产生",
      availability: "listed",
    },
    {
      riskLevel: 2,
      catalog: {
        authority: {
          kind: "test",
          id: "desktop-fixture",
        },
        identity: {
          id: "self-service",
          revision: "r1",
        },
        digest:
          "7a763c58eb07f82dd2f09db5ac7a2926c6ffa2262972c5a519b29414bcb565f3",
      },
      itemId: "maintenance",
      variantId: "test",
      kind: "tool",
      name: "维护窗口",
      description: "选择固定测试时段；不会安排系统任务。",
      category: "工具",
      resource: {
        reference: {
          id: "fixture-maintenance",
          revision: "r1",
        },
        versionDigest:
          "15f7f10668b4c73214413942b7f87e8a01596d7fa9ab829504b44eceae0e14c8",
        selector: {
          platform: "macos",
          architecture: "aarch64",
          key: "fixture",
        },
      },
      fields: {},
      inputSchema: {
        $schema: "https://json-schema.org/draft/2020-12/schema",
        additionalProperties: false,
        properties: {},
        required: [],
        type: "object",
      },
      display: {
        visibility: "allowed",
        requestability: "allowed",
        executability: "unknown",
      },
      reason: "S1 测试目录；最终裁决由提交时 Rust 校验产生",
      availability: "listed",
    },
    {
      riskLevel: 2,
      catalog: {
        authority: {
          kind: "test",
          id: "desktop-fixture",
        },
        identity: {
          id: "self-service",
          revision: "r1",
        },
        digest:
          "7a763c58eb07f82dd2f09db5ac7a2926c6ffa2262972c5a519b29414bcb565f3",
      },
      itemId: "office",
      variantId: "test",
      kind: "software",
      name: "办公套件",
      description: "确认本次测试动作后执行；不会安装软件。",
      category: "软件",
      resource: {
        reference: {
          id: "fixture-office",
          revision: "r1",
        },
        versionDigest:
          "3030918a3b2b48f626f2be192a97066424162a5ad52cf6b72da0d3373413f0ad",
        selector: {
          platform: "macos",
          architecture: "aarch64",
          key: "fixture",
        },
      },
      fields: {
        edition: {
          title: "软件版本",
          description: "测试版本选择",
          required: false,
          rule: {
            type: "string",
            minLength: 1,
            maxLength: 20,
            choices: ["standard", "professional"],
            default: "standard",
          },
        },
      },
      inputSchema: {
        $schema: "https://json-schema.org/draft/2020-12/schema",
        additionalProperties: false,
        properties: {
          edition: {
            default: "standard",
            description: "测试版本选择",
            enum: ["standard", "professional"],
            maxLength: 20,
            minLength: 1,
            title: "软件版本",
            type: "string",
          },
        },
        required: [],
        type: "object",
      },
      display: {
        visibility: "allowed",
        requestability: "allowed",
        executability: "unknown",
      },
      reason: "S1 测试目录；最终裁决由提交时 Rust 校验产生",
      availability: "listed",
    },
    {
      riskLevel: 0,
      catalog: {
        authority: {
          kind: "test",
          id: "desktop-fixture",
        },
        identity: {
          id: "self-service",
          revision: "r1",
        },
        digest:
          "7a763c58eb07f82dd2f09db5ac7a2926c6ffa2262972c5a519b29414bcb565f3",
      },
      itemId: "parameter-check",
      variantId: "test",
      kind: "tool",
      name: "参数复核",
      description: "重新核对原动作参数；更改参数需新建请求。",
      category: "工具",
      resource: {
        reference: {
          id: "fixture-parameter-check",
          revision: "r1",
        },
        versionDigest:
          "bb43d5a108d3996d0fa81f61eb7129cd75c0b8a1901cbe35fc53f129bbd79cd5",
        selector: {
          platform: "macos",
          architecture: "aarch64",
          key: "fixture",
        },
      },
      fields: {
        count: {
          title: "采样次数",
          description: "留空使用目录默认值",
          required: false,
          rule: {
            type: "integer",
            minimum: 1,
            maximum: 5,
            choices: null,
            default: 3,
          },
        },
        credential: {
          title: "测试凭据引用",
          description: "仅填写引用 ID 和版本，不输入密码正文",
          required: false,
          rule: {
            type: "secretReference",
          },
        },
        detail: {
          title: "包含详细信息",
          description: "仅模拟诊断说明",
          required: false,
          rule: {
            type: "boolean",
            default: false,
          },
        },
        host: {
          title: "诊断目标",
          description: "纯测试文本，不发起网络连接",
          required: true,
          rule: {
            type: "string",
            minLength: 3,
            maxLength: 100,
            choices: null,
            default: null,
          },
        },
      },
      inputSchema: {
        $schema: "https://json-schema.org/draft/2020-12/schema",
        additionalProperties: false,
        properties: {
          count: {
            default: 3,
            description: "留空使用目录默认值",
            maximum: 5,
            minimum: 1,
            title: "采样次数",
            type: "integer",
          },
          credential: {
            $schema: "https://json-schema.org/draft/2020-12/schema",
            additionalProperties: false,
            description: "仅填写引用 ID 和版本，不输入密码正文",
            properties: {
              id: {
                description:
                  "Opaque reference identity; the revision must be supplied separately.",
                maxLength: 128,
                minLength: 1,
                pattern: "^[A-Za-z0-9][A-Za-z0-9._:/-]*$",
                type: "string",
              },
              revision: {
                description:
                  "Exact immutable revision reference; does not resolve or follow a moving alias.",
                maxLength: 128,
                minLength: 1,
                pattern: "^[A-Za-z0-9][A-Za-z0-9._:/-]*$",
                type: "string",
              },
            },
            required: ["id", "revision"],
            title: "测试凭据引用",
            type: "object",
            writeOnly: true,
          },
          detail: {
            default: false,
            description: "仅模拟诊断说明",
            title: "包含详细信息",
            type: "boolean",
          },
          host: {
            description: "纯测试文本，不发起网络连接",
            maxLength: 100,
            minLength: 3,
            title: "诊断目标",
            type: "string",
          },
        },
        required: ["host"],
        type: "object",
      },
      display: {
        visibility: "allowed",
        requestability: "allowed",
        executability: "unknown",
      },
      reason: "S1 测试目录；最终裁决由提交时 Rust 校验产生",
      availability: "listed",
    },
    {
      riskLevel: 2,
      catalog: {
        authority: {
          kind: "test",
          id: "desktop-fixture",
        },
        identity: {
          id: "self-service",
          revision: "r1",
        },
        digest:
          "7a763c58eb07f82dd2f09db5ac7a2926c6ffa2262972c5a519b29414bcb565f3",
      },
      itemId: "restart",
      variantId: "test",
      kind: "tool",
      name: "重启提示",
      description: "选择稍后提醒或确认已阅读；不会重启设备。",
      category: "工具",
      resource: {
        reference: {
          id: "fixture-restart",
          revision: "r1",
        },
        versionDigest:
          "06110b6b40dd281f01b9824d4c4a73ec03a2c6a68e4c69e6f5bcbadaf6e6e8b3",
        selector: {
          platform: "macos",
          architecture: "aarch64",
          key: "fixture",
        },
      },
      fields: {},
      inputSchema: {
        $schema: "https://json-schema.org/draft/2020-12/schema",
        additionalProperties: false,
        properties: {},
        required: [],
        type: "object",
      },
      display: {
        visibility: "allowed",
        requestability: "allowed",
        executability: "unknown",
      },
      reason: "S1 测试目录；最终裁决由提交时 Rust 校验产生",
      availability: "listed",
    },
    {
      riskLevel: 1,
      catalog: {
        authority: {
          kind: "test",
          id: "desktop-fixture",
        },
        identity: {
          id: "self-service",
          revision: "r1",
        },
        digest:
          "7a763c58eb07f82dd2f09db5ac7a2926c6ffa2262972c5a519b29414bcb565f3",
      },
      itemId: "unknown",
      variantId: "test",
      kind: "tool",
      name: "未知效果示例",
      description: "固定未知结果，必须保持待核实，不能重跑掩盖。",
      category: "工具",
      resource: {
        reference: {
          id: "fixture-unknown",
          revision: "r1",
        },
        versionDigest:
          "47e1c9c969794a12afd03e09a5a35e1a241327973eeded3663e102e4cd3a9de2",
        selector: {
          platform: "macos",
          architecture: "aarch64",
          key: "fixture",
        },
      },
      fields: {},
      inputSchema: {
        $schema: "https://json-schema.org/draft/2020-12/schema",
        additionalProperties: false,
        properties: {},
        required: [],
        type: "object",
      },
      display: {
        visibility: "allowed",
        requestability: "allowed",
        executability: "unknown",
      },
      reason: "S1 测试目录；最终裁决由提交时 Rust 校验产生",
      availability: "listed",
    },
    {
      riskLevel: 3,
      catalog: {
        authority: {
          kind: "test",
          id: "desktop-fixture",
        },
        identity: {
          id: "self-service",
          revision: "r1",
        },
        digest:
          "7a763c58eb07f82dd2f09db5ac7a2926c6ffa2262972c5a519b29414bcb565f3",
      },
      itemId: "unsupported",
      variantId: "test",
      kind: "software",
      name: "不适用软件",
      description: "固定目标不适用样本。",
      category: "软件",
      resource: {
        reference: {
          id: "fixture-unsupported",
          revision: "r1",
        },
        versionDigest:
          "72a238978c1add51020e20a2026b57b044b66dfa910b47fdcf32f6bc0b684d4f",
        selector: {
          platform: "macos",
          architecture: "aarch64",
          key: "fixture",
        },
      },
      fields: {},
      inputSchema: {
        $schema: "https://json-schema.org/draft/2020-12/schema",
        additionalProperties: false,
        properties: {},
        required: [],
        type: "object",
      },
      display: {
        visibility: "allowed",
        requestability: "allowed",
        executability: "unknown",
      },
      reason: "S1 测试目录；最终裁决由提交时 Rust 校验产生",
      availability: "listed",
    },
    {
      riskLevel: 3,
      catalog: {
        authority: {
          kind: "test",
          id: "desktop-fixture",
        },
        identity: {
          id: "self-service",
          revision: "r1",
        },
        digest:
          "7a763c58eb07f82dd2f09db5ac7a2926c6ffa2262972c5a519b29414bcb565f3",
      },
      itemId: "withdrawn",
      variantId: "test",
      kind: "tool",
      name: "已下架工具",
      description: "历史目录记录，仅供浏览。",
      category: "工具",
      resource: {
        reference: {
          id: "fixture-withdrawn",
          revision: "r1",
        },
        versionDigest:
          "5c4fe62db86994f677567d36d1d9640fc0dc9c4b4e1f34cfea48a0a952a3378f",
        selector: {
          platform: "macos",
          architecture: "aarch64",
          key: "fixture",
        },
      },
      fields: {},
      inputSchema: {
        $schema: "https://json-schema.org/draft/2020-12/schema",
        additionalProperties: false,
        properties: {},
        required: [],
        type: "object",
      },
      display: {
        visibility: "allowed",
        requestability: "allowed",
        executability: "unknown",
      },
      reason: "S1 测试目录；最终裁决由提交时 Rust 校验产生",
      availability: "withdrawn",
    },
  ],
  requests: [],
  next: null,
  referencedRequests: [],
};
export default snapshot;
