// Generated by scripts/check-self-service.mjs --write; Rust owns these fixtures.
import type { Snapshot } from "./types";
const snapshot: Snapshot = {
  "mode": "fixture",
  "instanceId": "browser-preview",
  "targetLabel": "macOS arm64 · 测试设备 fixture-device · 测试用户 fixture-user",
  "catalog": [
    {
      "catalog": {
        "authority": {
          "kind": "test",
          "id": "desktop-fixture"
        },
        "identity": {
          "id": "self-service",
          "revision": "r1"
        },
        "digest": "def728f9c136e7b3dff4a70dab3fe7adcd7347522798cfaf27438cb7a5391fe6"
      },
      "itemId": "blocked",
      "variantId": "test",
      "kind": "software",
      "name": "受限软件",
      "description": "固定权限拒绝样本，无法申请或提交。",
      "category": "软件",
      "resource": {
        "reference": {
          "id": "fixture-blocked",
          "revision": "r1"
        },
        "versionDigest": "96c70d18ed44a6ab1dd066c4ea7039219ed4ffea2367870ed8b4518529662e44",
        "selector": {
          "platform": "macos",
          "architecture": "aarch64",
          "key": "fixture"
        }
      },
      "fields": {},
      "inputSchema": {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "additionalProperties": false,
        "properties": {},
        "required": [],
        "type": "object"
      },
      "display": {
        "visibility": "allowed",
        "requestability": "blocked",
        "executability": "blocked"
      },
      "reason": "固定权限拒绝样本，无法申请或提交。",
      "availability": "listed"
    },
    {
      "catalog": {
        "authority": {
          "kind": "test",
          "id": "desktop-fixture"
        },
        "identity": {
          "id": "self-service",
          "revision": "r1"
        },
        "digest": "def728f9c136e7b3dff4a70dab3fe7adcd7347522798cfaf27438cb7a5391fe6"
      },
      "itemId": "diagnostics",
      "variantId": "test",
      "kind": "tool",
      "name": "网络诊断",
      "description": "确认与隐私同意流程；不会发送网络请求。",
      "category": "工具",
      "resource": {
        "reference": {
          "id": "fixture-diagnostics",
          "revision": "r1"
        },
        "versionDigest": "eac22f39e822b9b78301322d2784b71306b769d92ce84a4bce291c2d9357b5b5",
        "selector": {
          "platform": "macos",
          "architecture": "aarch64",
          "key": "fixture"
        }
      },
      "fields": {
        "count": {
          "title": "采样次数",
          "description": "留空使用目录默认值",
          "required": false,
          "rule": {
            "type": "integer",
            "minimum": 1,
            "maximum": 5,
            "choices": null,
            "default": 3
          }
        },
        "credential": {
          "title": "测试凭据引用",
          "description": "仅填写引用 ID 和版本，不输入密码正文",
          "required": false,
          "rule": {
            "type": "secretReference"
          }
        },
        "detail": {
          "title": "包含详细信息",
          "description": "仅模拟诊断说明",
          "required": false,
          "rule": {
            "type": "boolean",
            "default": false
          }
        },
        "host": {
          "title": "诊断目标",
          "description": "纯测试文本，不发起网络连接",
          "required": true,
          "rule": {
            "type": "string",
            "minLength": 3,
            "maxLength": 100,
            "choices": null,
            "default": null
          }
        }
      },
      "inputSchema": {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "additionalProperties": false,
        "properties": {
          "count": {
            "default": 3,
            "description": "留空使用目录默认值",
            "maximum": 5,
            "minimum": 1,
            "title": "采样次数",
            "type": "integer"
          },
          "credential": {
            "$schema": "https://json-schema.org/draft/2020-12/schema",
            "additionalProperties": false,
            "description": "仅填写引用 ID 和版本，不输入密码正文",
            "properties": {
              "id": {
                "description": "Opaque reference identity; the revision must be supplied separately.",
                "maxLength": 128,
                "minLength": 1,
                "pattern": "^[A-Za-z0-9][A-Za-z0-9._:/-]*$",
                "type": "string"
              },
              "revision": {
                "description": "Exact immutable revision reference; does not resolve or follow a moving alias.",
                "maxLength": 128,
                "minLength": 1,
                "pattern": "^[A-Za-z0-9][A-Za-z0-9._:/-]*$",
                "type": "string"
              }
            },
            "required": [
              "id",
              "revision"
            ],
            "title": "测试凭据引用",
            "type": "object",
            "writeOnly": true
          },
          "detail": {
            "default": false,
            "description": "仅模拟诊断说明",
            "title": "包含详细信息",
            "type": "boolean"
          },
          "host": {
            "description": "纯测试文本，不发起网络连接",
            "maxLength": 100,
            "minLength": 3,
            "title": "诊断目标",
            "type": "string"
          }
        },
        "required": [
          "host"
        ],
        "type": "object"
      },
      "display": {
        "visibility": "allowed",
        "requestability": "allowed",
        "executability": "allowed"
      },
      "reason": "确认与隐私同意流程；不会发送网络请求。",
      "availability": "listed"
    },
    {
      "catalog": {
        "authority": {
          "kind": "test",
          "id": "desktop-fixture"
        },
        "identity": {
          "id": "self-service",
          "revision": "r1"
        },
        "digest": "def728f9c136e7b3dff4a70dab3fe7adcd7347522798cfaf27438cb7a5391fe6"
      },
      "itemId": "maintenance",
      "variantId": "test",
      "kind": "tool",
      "name": "维护窗口",
      "description": "选择固定测试时段；不会安排系统任务。",
      "category": "工具",
      "resource": {
        "reference": {
          "id": "fixture-maintenance",
          "revision": "r1"
        },
        "versionDigest": "15f7f10668b4c73214413942b7f87e8a01596d7fa9ab829504b44eceae0e14c8",
        "selector": {
          "platform": "macos",
          "architecture": "aarch64",
          "key": "fixture"
        }
      },
      "fields": {},
      "inputSchema": {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "additionalProperties": false,
        "properties": {},
        "required": [],
        "type": "object"
      },
      "display": {
        "visibility": "allowed",
        "requestability": "allowed",
        "executability": "allowed"
      },
      "reason": "选择固定测试时段；不会安排系统任务。",
      "availability": "listed"
    },
    {
      "catalog": {
        "authority": {
          "kind": "test",
          "id": "desktop-fixture"
        },
        "identity": {
          "id": "self-service",
          "revision": "r1"
        },
        "digest": "def728f9c136e7b3dff4a70dab3fe7adcd7347522798cfaf27438cb7a5391fe6"
      },
      "itemId": "office",
      "variantId": "test",
      "kind": "software",
      "name": "办公套件",
      "description": "申请测试软件，等待管理员批准；不会安装软件。",
      "category": "软件",
      "resource": {
        "reference": {
          "id": "fixture-office",
          "revision": "r1"
        },
        "versionDigest": "3030918a3b2b48f626f2be192a97066424162a5ad52cf6b72da0d3373413f0ad",
        "selector": {
          "platform": "macos",
          "architecture": "aarch64",
          "key": "fixture"
        }
      },
      "fields": {
        "edition": {
          "title": "软件版本",
          "description": "测试版本选择",
          "required": false,
          "rule": {
            "type": "string",
            "minLength": 1,
            "maxLength": 20,
            "choices": [
              "standard",
              "professional"
            ],
            "default": "standard"
          }
        }
      },
      "inputSchema": {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "additionalProperties": false,
        "properties": {
          "edition": {
            "default": "standard",
            "description": "测试版本选择",
            "enum": [
              "standard",
              "professional"
            ],
            "maxLength": 20,
            "minLength": 1,
            "title": "软件版本",
            "type": "string"
          }
        },
        "required": [],
        "type": "object"
      },
      "display": {
        "visibility": "allowed",
        "requestability": "allowed",
        "executability": "blocked"
      },
      "reason": "申请测试软件，等待管理员批准；不会安装软件。",
      "availability": "listed"
    },
    {
      "catalog": {
        "authority": {
          "kind": "test",
          "id": "desktop-fixture"
        },
        "identity": {
          "id": "self-service",
          "revision": "r1"
        },
        "digest": "def728f9c136e7b3dff4a70dab3fe7adcd7347522798cfaf27438cb7a5391fe6"
      },
      "itemId": "parameter-check",
      "variantId": "test",
      "kind": "tool",
      "name": "参数复核",
      "description": "重新核对原计划参数；更改参数需新建请求。",
      "category": "工具",
      "resource": {
        "reference": {
          "id": "fixture-parameter-check",
          "revision": "r1"
        },
        "versionDigest": "bb43d5a108d3996d0fa81f61eb7129cd75c0b8a1901cbe35fc53f129bbd79cd5",
        "selector": {
          "platform": "macos",
          "architecture": "aarch64",
          "key": "fixture"
        }
      },
      "fields": {
        "count": {
          "title": "采样次数",
          "description": "留空使用目录默认值",
          "required": false,
          "rule": {
            "type": "integer",
            "minimum": 1,
            "maximum": 5,
            "choices": null,
            "default": 3
          }
        },
        "credential": {
          "title": "测试凭据引用",
          "description": "仅填写引用 ID 和版本，不输入密码正文",
          "required": false,
          "rule": {
            "type": "secretReference"
          }
        },
        "detail": {
          "title": "包含详细信息",
          "description": "仅模拟诊断说明",
          "required": false,
          "rule": {
            "type": "boolean",
            "default": false
          }
        },
        "host": {
          "title": "诊断目标",
          "description": "纯测试文本，不发起网络连接",
          "required": true,
          "rule": {
            "type": "string",
            "minLength": 3,
            "maxLength": 100,
            "choices": null,
            "default": null
          }
        }
      },
      "inputSchema": {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "additionalProperties": false,
        "properties": {
          "count": {
            "default": 3,
            "description": "留空使用目录默认值",
            "maximum": 5,
            "minimum": 1,
            "title": "采样次数",
            "type": "integer"
          },
          "credential": {
            "$schema": "https://json-schema.org/draft/2020-12/schema",
            "additionalProperties": false,
            "description": "仅填写引用 ID 和版本，不输入密码正文",
            "properties": {
              "id": {
                "description": "Opaque reference identity; the revision must be supplied separately.",
                "maxLength": 128,
                "minLength": 1,
                "pattern": "^[A-Za-z0-9][A-Za-z0-9._:/-]*$",
                "type": "string"
              },
              "revision": {
                "description": "Exact immutable revision reference; does not resolve or follow a moving alias.",
                "maxLength": 128,
                "minLength": 1,
                "pattern": "^[A-Za-z0-9][A-Za-z0-9._:/-]*$",
                "type": "string"
              }
            },
            "required": [
              "id",
              "revision"
            ],
            "title": "测试凭据引用",
            "type": "object",
            "writeOnly": true
          },
          "detail": {
            "default": false,
            "description": "仅模拟诊断说明",
            "title": "包含详细信息",
            "type": "boolean"
          },
          "host": {
            "description": "纯测试文本，不发起网络连接",
            "maxLength": 100,
            "minLength": 3,
            "title": "诊断目标",
            "type": "string"
          }
        },
        "required": [
          "host"
        ],
        "type": "object"
      },
      "display": {
        "visibility": "allowed",
        "requestability": "allowed",
        "executability": "allowed"
      },
      "reason": "重新核对原计划参数；更改参数需新建请求。",
      "availability": "listed"
    },
    {
      "catalog": {
        "authority": {
          "kind": "test",
          "id": "desktop-fixture"
        },
        "identity": {
          "id": "self-service",
          "revision": "r1"
        },
        "digest": "def728f9c136e7b3dff4a70dab3fe7adcd7347522798cfaf27438cb7a5391fe6"
      },
      "itemId": "restart",
      "variantId": "test",
      "kind": "tool",
      "name": "重启提示",
      "description": "选择稍后提醒或确认已阅读；不会重启设备。",
      "category": "工具",
      "resource": {
        "reference": {
          "id": "fixture-restart",
          "revision": "r1"
        },
        "versionDigest": "06110b6b40dd281f01b9824d4c4a73ec03a2c6a68e4c69e6f5bcbadaf6e6e8b3",
        "selector": {
          "platform": "macos",
          "architecture": "aarch64",
          "key": "fixture"
        }
      },
      "fields": {},
      "inputSchema": {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "additionalProperties": false,
        "properties": {},
        "required": [],
        "type": "object"
      },
      "display": {
        "visibility": "allowed",
        "requestability": "allowed",
        "executability": "allowed"
      },
      "reason": "选择稍后提醒或确认已阅读；不会重启设备。",
      "availability": "listed"
    },
    {
      "catalog": {
        "authority": {
          "kind": "test",
          "id": "desktop-fixture"
        },
        "identity": {
          "id": "self-service",
          "revision": "r1"
        },
        "digest": "def728f9c136e7b3dff4a70dab3fe7adcd7347522798cfaf27438cb7a5391fe6"
      },
      "itemId": "unknown",
      "variantId": "test",
      "kind": "tool",
      "name": "未知效果示例",
      "description": "固定未知结果，必须保持待核实，不能重跑掩盖。",
      "category": "工具",
      "resource": {
        "reference": {
          "id": "fixture-unknown",
          "revision": "r1"
        },
        "versionDigest": "47e1c9c969794a12afd03e09a5a35e1a241327973eeded3663e102e4cd3a9de2",
        "selector": {
          "platform": "macos",
          "architecture": "aarch64",
          "key": "fixture"
        }
      },
      "fields": {},
      "inputSchema": {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "additionalProperties": false,
        "properties": {},
        "required": [],
        "type": "object"
      },
      "display": {
        "visibility": "allowed",
        "requestability": "allowed",
        "executability": "allowed"
      },
      "reason": "固定未知结果，必须保持待核实，不能重跑掩盖。",
      "availability": "listed"
    },
    {
      "catalog": {
        "authority": {
          "kind": "test",
          "id": "desktop-fixture"
        },
        "identity": {
          "id": "self-service",
          "revision": "r1"
        },
        "digest": "def728f9c136e7b3dff4a70dab3fe7adcd7347522798cfaf27438cb7a5391fe6"
      },
      "itemId": "unsupported",
      "variantId": "test",
      "kind": "software",
      "name": "不适用软件",
      "description": "固定目标不适用样本。",
      "category": "软件",
      "resource": {
        "reference": {
          "id": "fixture-unsupported",
          "revision": "r1"
        },
        "versionDigest": "72a238978c1add51020e20a2026b57b044b66dfa910b47fdcf32f6bc0b684d4f",
        "selector": {
          "platform": "macos",
          "architecture": "aarch64",
          "key": "fixture"
        }
      },
      "fields": {},
      "inputSchema": {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "additionalProperties": false,
        "properties": {},
        "required": [],
        "type": "object"
      },
      "display": {
        "visibility": "allowed",
        "requestability": "unsupportedTarget",
        "executability": "unsupportedTarget"
      },
      "reason": "固定目标不适用样本。",
      "availability": "listed"
    },
    {
      "catalog": {
        "authority": {
          "kind": "test",
          "id": "desktop-fixture"
        },
        "identity": {
          "id": "self-service",
          "revision": "r1"
        },
        "digest": "def728f9c136e7b3dff4a70dab3fe7adcd7347522798cfaf27438cb7a5391fe6"
      },
      "itemId": "withdrawn",
      "variantId": "test",
      "kind": "tool",
      "name": "已下架工具",
      "description": "历史目录记录，仅供浏览。",
      "category": "工具",
      "resource": {
        "reference": {
          "id": "fixture-withdrawn",
          "revision": "r1"
        },
        "versionDigest": "5c4fe62db86994f677567d36d1d9640fc0dc9c4b4e1f34cfea48a0a952a3378f",
        "selector": {
          "platform": "macos",
          "architecture": "aarch64",
          "key": "fixture"
        }
      },
      "fields": {},
      "inputSchema": {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "additionalProperties": false,
        "properties": {},
        "required": [],
        "type": "object"
      },
      "display": {
        "visibility": "allowed",
        "requestability": "blocked",
        "executability": "blocked"
      },
      "reason": "历史目录记录，仅供浏览。",
      "availability": "withdrawn"
    }
  ],
  "requests": [
    {
      "plan": {
        "requestId": "preview-diagnostics",
        "revision": 1,
        "planId": "plan-browser-preview-1",
        "digest": "a7fbf7214f14c580d7e54b47c329b8eef8a887ee950e2ee5657b0405d36af782",
        "itemId": "diagnostics",
        "title": "网络诊断",
        "action": "diagnose",
        "resource": {
          "reference": {
            "id": "fixture-diagnostics",
            "revision": "r1"
          },
          "versionDigest": "eac22f39e822b9b78301322d2784b71306b769d92ce84a4bce291c2d9357b5b5",
          "selector": {
            "platform": "macos",
            "architecture": "aarch64",
            "key": "fixture"
          }
        },
        "target": "macOS arm64 · 测试设备 fixture-device · 测试用户 fixture-user",
        "runAs": "测试用户 fixture-user；不使用宿主登录身份",
        "network": "禁止网络；不会发起连接",
        "dataScope": "无文件读写、无子进程；仅内存测试数据",
        "permission": "固定测试场景允许；不代表真实执行授权",
        "parameters": [
          {
            "label": "采样次数",
            "state": "使用目录默认值"
          },
          {
            "label": "测试凭据引用",
            "state": "未提供"
          },
          {
            "label": "包含详细信息",
            "state": "使用目录默认值"
          },
          {
            "label": "诊断目标",
            "state": "已提供"
          }
        ],
        "expiresAtUnixMs": 301000
      },
      "status": "waiting",
      "message": "等待用户处理交互",
      "interactions": [
        {
          "id": "interaction-plan-browser-preview-1-0",
          "kind": {
            "kind": "userConfirmation",
            "purpose": "continue"
          },
          "status": "pending",
          "message": "确认已阅读精确测试计划；此确认不构成管理员授权。",
          "expiresAtUnixMs": 301000,
          "options": []
        }
      ]
    },
    {
      "plan": {
        "requestId": "preview-office",
        "revision": 1,
        "planId": "plan-browser-preview-2",
        "digest": "942845add43fe5f340851da6c7f6427751f60a217b594af93d3484363f3c61c5",
        "itemId": "office",
        "title": "办公套件",
        "action": "install",
        "resource": {
          "reference": {
            "id": "fixture-office",
            "revision": "r1"
          },
          "versionDigest": "3030918a3b2b48f626f2be192a97066424162a5ad52cf6b72da0d3373413f0ad",
          "selector": {
            "platform": "macos",
            "architecture": "aarch64",
            "key": "fixture"
          }
        },
        "target": "macOS arm64 · 测试设备 fixture-device · 测试用户 fixture-user",
        "runAs": "测试用户 fixture-user；不使用宿主登录身份",
        "network": "禁止网络；不会发起连接",
        "dataScope": "无文件读写、无子进程；仅内存测试数据",
        "permission": "需管理员批准；本服务不签发批准",
        "parameters": [
          {
            "label": "软件版本",
            "state": "使用目录默认值"
          }
        ],
        "expiresAtUnixMs": 301000
      },
      "status": "approval",
      "message": "等待管理员批准；普通用户不能在此批准",
      "interactions": [
        {
          "id": "interaction-plan-browser-preview-2-0",
          "kind": {
            "kind": "administratorAuthorization",
            "request": "fixture-admin-request"
          },
          "status": "pending",
          "message": "等待外部管理员批准。本测试服务不签发批准，也不提供自我批准入口。",
          "expiresAtUnixMs": 301000,
          "options": []
        }
      ]
    },
    {
      "plan": {
        "requestId": "preview-restart",
        "revision": 1,
        "planId": "plan-browser-preview-3",
        "digest": "db9a3b56a50c476c95ac2099c6fabde9ebe2905fefa06e00889dc56a8e0887ac",
        "itemId": "restart",
        "title": "重启提示",
        "action": "diagnose",
        "resource": {
          "reference": {
            "id": "fixture-restart",
            "revision": "r1"
          },
          "versionDigest": "06110b6b40dd281f01b9824d4c4a73ec03a2c6a68e4c69e6f5bcbadaf6e6e8b3",
          "selector": {
            "platform": "macos",
            "architecture": "aarch64",
            "key": "fixture"
          }
        },
        "target": "macOS arm64 · 测试设备 fixture-device · 测试用户 fixture-user",
        "runAs": "测试用户 fixture-user；不使用宿主登录身份",
        "network": "禁止网络；不会发起连接",
        "dataScope": "无文件读写、无子进程；仅内存测试数据",
        "permission": "固定测试场景允许；不代表真实执行授权",
        "parameters": [],
        "expiresAtUnixMs": 301000
      },
      "status": "waiting",
      "message": "等待用户处理交互",
      "interactions": [
        {
          "id": "interaction-plan-browser-preview-3-0",
          "kind": {
            "kind": "restartPrompt",
            "options": "fixture-restart-r1"
          },
          "status": "pending",
          "message": "待重启仅为固定提示；选择不会触发重启。",
          "expiresAtUnixMs": 301000,
          "options": [
            {
              "id": "later",
              "label": "稍后提醒"
            },
            {
              "id": "acknowledged",
              "label": "已阅读提示"
            }
          ]
        }
      ]
    },
    {
      "plan": {
        "requestId": "preview-unknown",
        "revision": 1,
        "planId": "plan-browser-preview-4",
        "digest": "a32c22aaacccb202338a6f5d2a673622c431fb30a588433de50cdbb31f85569e",
        "itemId": "unknown",
        "title": "未知效果示例",
        "action": "diagnose",
        "resource": {
          "reference": {
            "id": "fixture-unknown",
            "revision": "r1"
          },
          "versionDigest": "47e1c9c969794a12afd03e09a5a35e1a241327973eeded3663e102e4cd3a9de2",
          "selector": {
            "platform": "macos",
            "architecture": "aarch64",
            "key": "fixture"
          }
        },
        "target": "macOS arm64 · 测试设备 fixture-device · 测试用户 fixture-user",
        "runAs": "测试用户 fixture-user；不使用宿主登录身份",
        "network": "禁止网络；不会发起连接",
        "dataScope": "无文件读写、无子进程；仅内存测试数据",
        "permission": "固定测试场景允许；不代表真实执行授权",
        "parameters": [],
        "expiresAtUnixMs": 301000
      },
      "status": "unknownEffect",
      "message": "固定未知效果样本：等待核实，不能宣称成功或自动重跑",
      "interactions": []
    }
  ]
};
export default snapshot;
