// Generated by scripts/check-self-service-bindings.mjs --write; edit Rust owners instead.

/**
 * Lowercase SHA-256 bytes expressed as hex; a digest alone grants no trust.
 *
 * This interface was referenced by `SelfServiceCommands`'s JSON-Schema
 * via the `definition` "Digest".
 */
export type Digest = string;
/**
 * Immutable local plan identity.
 *
 * This interface was referenced by `SelfServiceCommands`'s JSON-Schema
 * via the `definition` "PlanId".
 */
export type PlanId = string;
/**
 * Local execution request identity.
 *
 * This interface was referenced by `SelfServiceCommands`'s JSON-Schema
 * via the `definition` "RequestId".
 */
export type RequestId = string;
/**
 * Exact waiting reason. Referenced choices and schemas belong to the caller.
 *
 * This interface was referenced by `SelfServiceCommands`'s JSON-Schema
 * via the `definition` "Kind".
 */
export type Kind =
  | {
      kind: "userConfirmation";
      /**
       * The bounded purpose of confirmation.
       */
      purpose: ConfirmationPurpose;
    }
  | {
      kind: "privacyConsent";
      /**
       * Exact privacy scope revision reference.
       */
      scope: Reference;
    }
  | {
      kind: "administratorAuthorization";
      /**
       * Exact approval request reference.
       */
      request: Reference;
    }
  | {
      kind: "parameterInput";
      /**
       * Exact schema reference; no schema engine is embedded here.
       */
      schema: Reference;
    }
  | {
      kind: "maintenanceWindow";
      /**
       * Exact available choices reference.
       */
      options: Reference;
    }
  | {
      kind: "restartPrompt";
      /**
       * Exact available choices reference.
       */
      options: Reference;
    };
/**
 * User confirmation cannot stand in for privacy consent or administrator authorization.
 *
 * This interface was referenced by `SelfServiceCommands`'s JSON-Schema
 * via the `definition` "ConfirmationPurpose".
 */
export type ConfirmationPurpose = "continue" | "closeApplication";
/**
 * Bounded opaque interaction-owned reference; not a task identity or authority proof.
 *
 * This interface was referenced by `SelfServiceCommands`'s JSON-Schema
 * via the `definition` "Reference".
 */
export type Reference = string;
/**
 * This interface was referenced by `SelfServiceCommands`'s JSON-Schema
 * via the `definition` "InteractionStatus".
 */
export type InteractionStatus =
  | "pending"
  | "answered"
  | "cancelled"
  | "expired";
/**
 * Opaque local reference identifier; syntax validity is not authenticity.
 *
 * This interface was referenced by `SelfServiceCommands`'s JSON-Schema
 * via the `definition` "Id".
 */
export type Id = string;
/**
 * Exact architecture selector; support remains a capability-owner decision.
 *
 * This interface was referenced by `SelfServiceCommands`'s JSON-Schema
 * via the `definition` "Architecture".
 */
export type Architecture = "x86_64" | "aarch64";
/**
 * Target OS semantics for validation; an enum value is not a platform support claim.
 *
 * This interface was referenced by `SelfServiceCommands`'s JSON-Schema
 * via the `definition` "Platform".
 */
export type Platform = "windows" | "macos" | "linux";
/**
 * This interface was referenced by `SelfServiceCommands`'s JSON-Schema
 * via the `definition` "RequestStatus".
 */
export type RequestStatus =
  | "waiting"
  | "approval"
  | "complete"
  | "stopped"
  | "restartRequired"
  | "unknownEffect";
/**
 * Separate namespaces: none of these serializable references authenticates its issuer.
 *
 * This interface was referenced by `SelfServiceCommands`'s JSON-Schema
 * via the `definition` "Authority".
 */
export type Authority =
  | {
      /**
       * Authority reference in this variant namespace; no proof of issuer authenticity.
       */
      id: Id;
      kind: "local";
    }
  | {
      /**
       * Authority reference in this variant namespace; no proof of issuer authenticity.
       */
      id: Id;
      kind: "enterprise";
      /**
       * Explicit enterprise tenant reference; local/test authority never fabricates a tenant.
       */
      tenant: Id;
    }
  | {
      /**
       * Authority reference in this variant namespace; no proof of issuer authenticity.
       */
      id: Id;
      kind: "test";
    };
/**
 * This interface was referenced by `SelfServiceCommands`'s JSON-Schema
 * via the `definition` "FieldInput".
 */
export type FieldInput =
  | {
      kind: "text";
      value: string;
    }
  | {
      kind: "integer";
      value: string;
    }
  | {
      kind: "boolean";
      value: boolean;
    }
  | {
      id: string;
      kind: "secretReference";
      revision: string;
    };
/**
 * This interface was referenced by `SelfServiceCommands`'s JSON-Schema
 * via the `definition` "Answer".
 */
export type Answer =
  | {
      accepted: boolean;
      kind: "confirmation";
    }
  | {
      accepted: boolean;
      kind: "privacyConsent";
    }
  | {
      kind: "choice";
      selection: string;
    }
  | {
      fields: {
        [k: string]: FieldInput;
      };
      kind: "parameters";
    }
  | {
      kind: "cancel";
    };
/**
 * This interface was referenced by `SelfServiceCommands`'s JSON-Schema
 * via the `definition` "Availability".
 */
export type Availability = "listed" | "withdrawn" | "expired";
/**
 * Closed owner-provided display decision for one axis; never a permission.
 *
 * This interface was referenced by `SelfServiceCommands`'s JSON-Schema
 * via the `definition` "DisplayDecision".
 */
export type DisplayDecision =
  | "unknown"
  | "allowed"
  | "missingCapability"
  | "unsupportedTarget"
  | "unresolvedResource"
  | "blocked";
/**
 * Supported value grammar. Secret references are the only permitted object-valued parameter.
 *
 * This interface was referenced by `SelfServiceCommands`'s JSON-Schema
 * via the `definition` "ParameterRule".
 */
export type ParameterRule =
  | {
      /**
       * Optional nonempty unique allowed values, all within the length constraints.
       */
      choices: string[] | null;
      /**
       * Valid default for an optional field only.
       */
      default: string | null;
      /**
       * Inclusive maximum character count.
       */
      maxLength: number;
      /**
       * Inclusive minimum character count.
       */
      minLength: number;
      type: "string";
    }
  | {
      /**
       * Optional nonempty unique allowed safe integers.
       */
      choices: number[] | null;
      /**
       * Valid default for an optional field only.
       */
      default: number | null;
      /**
       * Inclusive safe integer maximum.
       */
      maximum: number;
      /**
       * Inclusive safe integer minimum.
       */
      minimum: number;
      type: "integer";
    }
  | {
      /**
       * Valid default for an optional field only.
       */
      default: boolean | null;
      type: "boolean";
    }
  | {
      type: "secretReference";
    };
/**
 * Display classification, independent of backend Resource kinds.
 *
 * This interface was referenced by `SelfServiceCommands`'s JSON-Schema
 * via the `definition` "CatalogKind".
 */
export type CatalogKind = "software" | "script" | "tool";
/**
 * This interface was referenced by `SelfServiceCommands`'s JSON-Schema
 * via the `definition` "ServiceMode".
 */
export type ServiceMode = "fixture" | "s1";

export interface SelfServiceCommands {
  self_service_approve: Command3;
  self_service_cancel: Command3;
  self_service_preview: Command2;
  self_service_respond: Command4;
  self_service_snapshot: Command;
  self_service_submit: Command3;
}
/**
 * This interface was referenced by `SelfServiceCommands`'s JSON-Schema
 * via the `definition` "Command3".
 */
export interface Command3 {
  input: Submission;
  output: RequestView;
}
/**
 * This interface was referenced by `SelfServiceCommands`'s JSON-Schema
 * via the `definition` "Submission".
 */
export interface Submission {
  digest: Digest;
  instanceId: string;
  planId: PlanId;
  requestId: RequestId;
}
/**
 * This interface was referenced by `SelfServiceCommands`'s JSON-Schema
 * via the `definition` "RequestView".
 */
export interface RequestView {
  interactions: Interaction[];
  message: string;
  plan: Plan;
  status: RequestStatus;
}
/**
 * This interface was referenced by `SelfServiceCommands`'s JSON-Schema
 * via the `definition` "Interaction".
 */
export interface Interaction {
  expiresAtUnixMs: number;
  id: string;
  kind: Kind;
  message: string;
  options: Choice[];
  status: InteractionStatus;
}
/**
 * This interface was referenced by `SelfServiceCommands`'s JSON-Schema
 * via the `definition` "Choice".
 */
export interface Choice {
  id: string;
  label: string;
}
/**
 * This interface was referenced by `SelfServiceCommands`'s JSON-Schema
 * via the `definition` "Plan".
 */
export interface Plan {
  action: Id;
  dataScope: string;
  digest: Digest;
  expiresAtUnixMs: number;
  itemId: Id;
  network: string;
  parameters: ParameterSummary[];
  permission: string;
  planId: PlanId;
  requestId: RequestId;
  resource: ResourceBinding;
  revision: number;
  runAs: string;
  target: string;
  title: string;
}
/**
 * This interface was referenced by `SelfServiceCommands`'s JSON-Schema
 * via the `definition` "ParameterSummary".
 */
export interface ParameterSummary {
  label: string;
  state: string;
}
/**
 * Immutable resource definition pin scoped by the containing catalog authority.
 *
 * This interface was referenced by `SelfServiceCommands`'s JSON-Schema
 * via the `definition` "ResourceBinding".
 */
export interface ResourceBinding {
  /**
   * Owner's resource identity and immutable revision; never a moving alias lookup.
   */
  reference: VersionedRef;
  /**
   * Exact variant within that resource version.
   */
  selector: ResourceSelector;
  /**
   * SHA-256 of the owner's resource version definition, NOT file byte SHA-256.
   */
  versionDigest: Digest;
}
/**
 * Exact resource/configuration reference. Resolution and authenticity belong to the owner.
 *
 * This interface was referenced by `SelfServiceCommands`'s JSON-Schema
 * via the `definition` "VersionedRef".
 */
export interface VersionedRef {
  /**
   * Opaque reference identity; the revision must be supplied separately.
   */
  id: Id;
  /**
   * Exact immutable revision reference; does not resolve or follow a moving alias.
   */
  revision: Id;
}
/**
 * Exact variant coordinates, not a platform support assertion.
 *
 * This interface was referenced by `SelfServiceCommands`'s JSON-Schema
 * via the `definition` "ResourceSelector".
 */
export interface ResourceSelector {
  /**
   * Exact target architecture.
   */
  architecture: Architecture;
  /**
   * Opaque resource variant key, separate from catalog operation ID and action.
   */
  key: Id;
  /**
   * Target platform namespace.
   */
  platform: Platform;
}
/**
 * This interface was referenced by `SelfServiceCommands`'s JSON-Schema
 * via the `definition` "Command2".
 */
export interface Command2 {
  input: Draft;
  output: Plan;
}
/**
 * This interface was referenced by `SelfServiceCommands`'s JSON-Schema
 * via the `definition` "Draft".
 */
export interface Draft {
  catalog: CatalogRef;
  fields: {
    [k: string]: FieldInput;
  };
  instanceId: string;
  itemId: Id;
  requestId: RequestId;
  revision: number;
  variantId: Id;
}
/**
 * Exact catalog content identity. It is neither a signature nor an authorization token.
 *
 * This interface was referenced by `SelfServiceCommands`'s JSON-Schema
 * via the `definition` "CatalogRef".
 */
export interface CatalogRef {
  /**
   * Complete namespace including enterprise tenant when applicable.
   */
  authority: Authority;
  /**
   * Computed canonical catalog SHA-256.
   */
  digest: Digest;
  /**
   * Catalog ID/revision, not resource version or format version.
   */
  identity: VersionedRef;
}
/**
 * This interface was referenced by `SelfServiceCommands`'s JSON-Schema
 * via the `definition` "Command4".
 */
export interface Command4 {
  input: Reply;
  output: RequestView;
}
/**
 * This interface was referenced by `SelfServiceCommands`'s JSON-Schema
 * via the `definition` "Reply".
 */
export interface Reply {
  answer: Answer;
  commandId: Reference;
  instanceId: string;
  interactionId: string;
  requestId: RequestId;
}
/**
 * This interface was referenced by `SelfServiceCommands`'s JSON-Schema
 * via the `definition` "Command".
 */
export interface Command {
  input: null;
  output: Snapshot;
}
/**
 * This interface was referenced by `SelfServiceCommands`'s JSON-Schema
 * via the `definition` "Snapshot".
 */
export interface Snapshot {
  catalog: CatalogItem[];
  instanceId: string;
  mode: ServiceMode;
  requests: RequestView[];
  targetLabel: string;
}
/**
 * This interface was referenced by `SelfServiceCommands`'s JSON-Schema
 * via the `definition` "CatalogItem".
 */
export interface CatalogItem {
  availability: Availability;
  catalog: CatalogRef;
  category: string;
  description: string;
  display: DisplayStatus;
  fields: {
    [k: string]: Parameter;
  };
  inputSchema: unknown;
  itemId: Id;
  kind: CatalogKind;
  name: string;
  reason: string;
  resource: ResourceBinding;
  variantId: Id;
}
/**
 * Independent display axes from the capability/authorization owner, never execution authority.
 * Hosts must authenticate the source and reauthorize at execution, including for Allowed values.
 *
 * This interface was referenced by `SelfServiceCommands`'s JSON-Schema
 * via the `definition` "DisplayStatus".
 */
export interface DisplayStatus {
  /**
   * Whether owner preflight currently reports this exact choice as executable.
   */
  executability: DisplayDecision;
  /**
   * Whether this target can request this exact choice.
   */
  requestability: DisplayDecision;
  /**
   * Whether this exact choice should be shown to this target.
   */
  visibility: DisplayDecision;
}
/**
 * A field's display metadata and single source of validation semantics.
 *
 * This interface was referenced by `undefined`'s JSON-Schema definition
 * via the `patternProperty` "^[A-Za-z0-9][A-Za-z0-9._:/-]*$".
 *
 * This interface was referenced by `SelfServiceCommands`'s JSON-Schema
 * via the `definition` "Parameter".
 */
export interface Parameter {
  /**
   * Plain-text field help, never model instructions.
   */
  description: string;
  /**
   * Required fields cannot have defaults.
   */
  required: boolean;
  /**
   * Closed first-version rules; adding a rule requires updating every projection/validator.
   */
  rule: ParameterRule;
  /**
   * Nonempty plain-text field label.
   */
  title: string;
}

export type Decision = CatalogItem["display"]["visibility"];
export type SelfServicePort = {
  [K in keyof SelfServiceCommands as K extends `self_service_${infer M}`
    ? M
    : never]: SelfServiceCommands[K]["input"] extends null
    ? () => Promise<SelfServiceCommands[K]["output"]>
    : (
        input: SelfServiceCommands[K]["input"],
      ) => Promise<SelfServiceCommands[K]["output"]>;
};
