// Generated by scripts/check-self-service-bindings.mjs --write; edit Rust owners instead.

/**
 * Local execution request identity.
 *
 * This interface was referenced by `SelfServiceCommands`'s JSON-Schema
 * via the `definition` "RequestId".
 */
export type RequestId = string;
/**
 * Query result spanning preparation and actual execution without inventing a frozen plan.
 *
 * This interface was referenced by `SelfServiceCommands`'s JSON-Schema
 * via the `definition` "BackendTaskView".
 */
export type BackendTaskView =
  | {
      kind: "pending";
      /**
       * Original offer, caller binding and durable preparation state.
       */
      value: BackendRequest;
    }
  | {
      kind: "execution";
      /**
       * Real frozen input projection and lifecycle facts.
       */
      value: ExecutionTaskDetails;
    };
/**
 * Closed preparation diagnosis without backend bodies or local paths.
 *
 * This interface was referenced by `SelfServiceCommands`'s JSON-Schema
 * via the `definition` "BackendRequestFailure".
 */
export type BackendRequestFailure =
  | "preparationFailed"
  | "interrupted"
  | "expired"
  | "revoked";
/**
 * Opaque local reference identifier; syntax validity is not authenticity.
 *
 * This interface was referenced by `SelfServiceCommands`'s JSON-Schema
 * via the `definition` "Id".
 */
export type Id = string;
/**
 * Lowercase SHA-256 bytes expressed as hex; a digest alone grants no trust.
 *
 * This interface was referenced by `SelfServiceCommands`'s JSON-Schema
 * via the `definition` "Digest".
 */
export type Digest = string;
/**
 * Safe preview bound to the complete signed offer revision.
 *
 * This interface was referenced by `SelfServiceCommands`'s JSON-Schema
 * via the `definition` "BackendTaskSummary".
 */
export type BackendTaskSummary =
  | {
      /**
       * Account class selected by the backend.
       */
      identity: BackendIdentity;
      kind: "script";
    }
  | {
      /**
       * Install, uninstall or detection intent.
       */
      intent: SoftwareOperation;
      kind: "software";
      /**
       * Ordered prerequisites and final package.
       */
      steps: BackendStepSummary[];
    };
/**
 * Display-only account class, never OS identity evidence.
 *
 * This interface was referenced by `SelfServiceCommands`'s JSON-Schema
 * via the `definition` "BackendIdentity".
 */
export type BackendIdentity = "system" | "user";
/**
 * One backend software intent, independent of individual process exit codes.
 *
 * This interface was referenced by `SelfServiceCommands`'s JSON-Schema
 * via the `definition` "SoftwareOperation".
 */
export type SoftwareOperation = "install" | "detect" | "uninstall";
/**
 * Preparation state only; none of these values authorizes physical execution.
 *
 * This interface was referenced by `SelfServiceCommands`'s JSON-Schema
 * via the `definition` "BackendRequestState".
 */
export type BackendRequestState =
  | "proposed"
  | "selected"
  | "submitting"
  | "failed"
  | "cancelled";
/**
 * Provenance for a task already authorized by the backend; never a local enterprise approval.
 *
 * This interface was referenced by `SelfServiceCommands`'s JSON-Schema
 * via the `definition` "BackendTrigger".
 */
export type BackendTrigger =
  | {
      kind: "automatic";
    }
  | {
      kind: "human";
      /**
       * Actual native account and login session, supplied by ingress.
       */
      osSession: OsSessionRef;
    }
  | {
      /**
       * Native AI connection configuration, not a provider identity grant.
       */
      config: VersionedRef;
      /**
       * Conversation reference used for audit correlation.
       */
      conversation: Id;
      kind: "ai";
      /**
       * Actual native account and login session, supplied by ingress.
       */
      osSession: OsSessionRef;
      /**
       * Tool request reference used for audit correlation.
       */
      toolCall: Id;
    };
/**
 * Target OS semantics for validation; an enum value is not a platform support claim.
 *
 * This interface was referenced by `SelfServiceCommands`'s JSON-Schema
 * via the `definition` "Platform".
 */
export type Platform = "windows" | "macos" | "linux";
/**
 * Device reference, not verified registration evidence.
 *
 * This interface was referenced by `SelfServiceCommands`'s JSON-Schema
 * via the `definition` "DeviceId".
 */
export type DeviceId = string;
/**
 * Safe counts only; individual paths and network destinations remain protected.
 *
 * This interface was referenced by `SelfServiceCommands`'s JSON-Schema
 * via the `definition` "AccessSummary".
 */
export type AccessSummary =
  | {
      kind: "osIdentity";
    }
  | {
      /**
       * Required child process allowance.
       */
      allowChildProcesses: boolean;
      kind: "restricted";
      /**
       * Whether networking is completely denied.
       */
      networkDenied: boolean;
      /**
       * Number of exact allowlisted destinations; never their values.
       */
      networkDestinationCount: number;
      /**
       * Number of declared read paths.
       */
      readPathCount: number;
      /**
       * Required isolation; this is not an observation that enforcement succeeded.
       */
      requireSandbox: boolean;
      /**
       * Number of declared write paths.
       */
      writePathCount: number;
    };
/**
 * Product actor reference, not an authenticated principal.
 *
 * This interface was referenced by `SelfServiceCommands`'s JSON-Schema
 * via the `definition` "ActorId".
 */
export type ActorId = string;
/**
 * Separate namespaces: none of these serializable references authenticates its issuer.
 *
 * This interface was referenced by `SelfServiceCommands`'s JSON-Schema
 * via the `definition` "Authority".
 */
export type Authority =
  | {
      /**
       * Authority reference in this variant namespace; no proof of issuer authenticity.
       */
      id: Id;
      kind: "local";
    }
  | {
      /**
       * Authority reference in this variant namespace; no proof of issuer authenticity.
       */
      id: Id;
      kind: "enterprise";
      /**
       * Explicit enterprise tenant reference; local/test authority never fabricates a tenant.
       */
      tenant: Id;
    }
  | {
      /**
       * Authority reference in this variant namespace; no proof of issuer authenticity.
       */
      id: Id;
      kind: "test";
    };
/**
 * Safe execution semantics for task presentation; it never grants execution permission.
 *
 * This interface was referenced by `SelfServiceCommands`'s JSON-Schema
 * via the `definition` "ExecutionSummary".
 */
export type ExecutionSummary =
  | {
      /**
       * Fixed backend operation.
       */
      intent: SoftwareOperation;
      kind: "softwareProgram";
      /**
       * Safe step identities, without launch inputs or paths.
       */
      steps: SoftwareStepSummary[];
    }
  | {
      kind: "process";
    };
/**
 * The supported software adapters. No plugin names or command strings are accepted.
 *
 * This interface was referenced by `SelfServiceCommands`'s JSON-Schema
 * via the `definition` "SoftwareKind".
 */
export type SoftwareKind =
  | "msi"
  | "winget"
  | "pkg"
  | "homebrew"
  | "windowsBundle"
  | "macosBundle";
/**
 * Exact ecosystem text: no SemVer, case folding, alias lookup or normalization.
 * Accepts 1..=1024 UTF-8 bytes without control characters, including '+' and '~'.
 *
 * This interface was referenced by `SelfServiceCommands`'s JSON-Schema
 * via the `definition` "PackageValue".
 */
export type PackageValue = string;
/**
 * Requested execution identity; authorization and actual identity switching are external.
 *
 * This interface was referenced by `SelfServiceCommands`'s JSON-Schema
 * via the `definition` "RunAs".
 */
export type RunAs =
  | {
      /**
       * Explicit account reference; never implicitly mapped to a product actor by name or email.
       */
      account: OsAccountRef;
      kind: "user";
    }
  | {
      kind: "system";
      /**
       * OS namespace of this reference or target; does not assert platform support.
       */
      platform: Platform;
    };
/**
 * Request origin and account provenance; never grants the product actor additional authority.
 *
 * This interface was referenced by `SelfServiceCommands`'s JSON-Schema
 * via the `definition` "Initiator".
 */
export type Initiator =
  | {
      /**
       * Exact server execution attempt.
       */
      attempt: Id;
      kind: "backend";
      /**
       * Exact server task, independently verified by the host.
       */
      task: Id;
      /**
       * Authenticated local trigger or automatic backend dispatch.
       */
      trigger: BackendTrigger;
    }
  | {
      kind: "human";
      /**
       * Originating OS account/session reference, separate from requested run-as identity.
       */
      osSession: OsSessionRef;
    }
  | {
      /**
       * Exact connection configuration used at initiation; no external account identity.
       */
      config: VersionedRef;
      /**
       * Originating AI conversation reference in the provider namespace.
       */
      conversation: Id;
      kind: "ai";
      /**
       * Originating OS account/session reference, separate from requested run-as identity.
       */
      osSession: OsSessionRef;
      /**
       * Provider namespace, independent of product authentication.
       */
      provider: Id;
      /**
       * Originating tool-call reference; cannot act as a product approval.
       */
      toolCall: Id;
    }
  | {
      kind: "policy";
      /**
       * Exact policy revision associated with this request or audit decision.
       */
      policy: VersionedRef;
    };
/**
 * This interface was referenced by `SelfServiceCommands`'s JSON-Schema
 * via the `definition` "LocalContractV5".
 */
export type LocalContractV5 = 5;
/**
 * Required target user-session availability, independent of the originating login.
 *
 * This interface was referenced by `SelfServiceCommands`'s JSON-Schema
 * via the `definition` "SessionRequirement".
 */
export type SessionRequirement =
  | {
      kind: "notRequired";
    }
  | {
      /**
       * Exact account whose session is required, not inferred from the initiator.
       */
      account: OsAccountRef;
      kind: "activeUser";
      /**
       * Exact native login session; a new login for the same account is not interchangeable.
       */
      session: Id;
    };
/**
 * Device-wide or explicit-user scope of the requested operation.
 *
 * This interface was referenced by `SelfServiceCommands`'s JSON-Schema
 * via the `definition` "TargetScope".
 */
export type TargetScope =
  | {
      kind: "device";
    }
  | {
      /**
       * Explicit account reference; never implicitly mapped to a product actor by name or email.
       */
      account: OsAccountRef;
      kind: "user";
    };
/**
 * Value-only admission result; policy/rule/approver details remain in privileged audit.
 *
 * This interface was referenced by `SelfServiceCommands`'s JSON-Schema
 * via the `definition` "AdmissionStatus".
 */
export type AdmissionStatus = "admitted" | "denied" | "approvalRequired";
/**
 * Verified assessment of the whole controlled attempt, not text from tool output.
 *
 * This interface was referenced by `SelfServiceCommands`'s JSON-Schema
 * via the `definition` "EffectAssessment".
 */
export type EffectAssessment =
  | "noEffect"
  | "satisfied"
  | "notSatisfied"
  | "unknown";
/**
 * Execution attempt correlation identity.
 *
 * This interface was referenced by `SelfServiceCommands`'s JSON-Schema
 * via the `definition` "AttemptId".
 */
export type AttemptId = string;
/**
 * Closed first-delivery diagnostics. These are not observations of termination or effects.
 *
 * This interface was referenced by `SelfServiceCommands`'s JSON-Schema
 * via the `definition` "DispatchCause".
 */
export type DispatchCause =
  | "capabilityUnavailable"
  | "clockUnavailable"
  | "cancelled"
  | {
      limit: LimitReason;
    }
  | "staleRevision"
  | "runnerMismatch"
  | "configurationUnavailable"
  | "authorityUnavailable"
  | "lifecycleChanged"
  | "runnerRejected"
  | "deliveryUnknown"
  | "runnerError";
/**
 * Explicit reason a validity or cumulative budget bound prevents work.
 *
 * This interface was referenced by `SelfServiceCommands`'s JSON-Schema
 * via the `definition` "LimitReason".
 */
export type LimitReason =
  | "notYetValid"
  | "expired"
  | "timeout"
  | "output"
  | "attempts";
/**
 * Recorded observation category. None of these references verifies a real-world effect.
 *
 * This interface was referenced by `SelfServiceCommands`'s JSON-Schema
 * via the `definition` "EvidenceKind".
 */
export type EvidenceKind = "testResult" | "processExited" | "stateObserved";
/**
 * Explicit execution provenance; test effects never become real effects.
 *
 * This interface was referenced by `SelfServiceCommands`'s JSON-Schema
 * via the `definition` "ExecutionMode".
 */
export type ExecutionMode = "test" | "real";
/**
 * Safe presentation of C09 facts, not a second persisted state machine.
 *
 * This interface was referenced by `SelfServiceCommands`'s JSON-Schema
 * via the `definition` "TaskPhase".
 */
export type TaskPhase =
  | "waiting"
  | "admissionDenied"
  | "approvalRequired"
  | "confirmationRequired"
  | "accepted"
  | "running"
  | "outcomeUnknown"
  | "executionEnded"
  | "verified"
  | "failedBeforeDispatch"
  | "cancelled";
/**
 * Why a bounded process owner stopped collecting output.
 *
 * This interface was referenced by `SelfServiceCommands`'s JSON-Schema
 * via the `definition` "ProcessEnd".
 */
export type ProcessEnd =
  | "rejected"
  | "exited"
  | "cancelled"
  | "timedOut"
  | "outputLimit"
  | "unknown";
/**
 * Closed, value-free mechanism diagnosis, independent of cancellation, exit and effect.
 *
 * This interface was referenced by `SelfServiceCommands`'s JSON-Schema
 * via the `definition` "ProcessFailureKind".
 */
export type ProcessFailureKind =
  | "none"
  | "denied"
  | "unbound"
  | "capability"
  | "unsupported"
  | "invalidInput"
  | "capacity"
  | "conflict"
  | "unavailable"
  | "runtime"
  | "spawn"
  | "inputDelivery"
  | "capture"
  | "supervision"
  | "outputValidation";
/**
 * Quality of the captured result, independent from the exit code.
 *
 * This interface was referenced by `SelfServiceCommands`'s JSON-Schema
 * via the `definition` "OutputQuality".
 */
export type OutputQuality = "complete" | "truncated" | "failed" | "partial";
/**
 * Safe software diagnostic; contains no paths, source coordinates or captured output.
 *
 * This interface was referenced by `SelfServiceCommands`'s JSON-Schema
 * via the `definition` "SoftwareDiagnostic".
 */
export type SoftwareDiagnostic =
  | "awaitingDetection"
  | "restartPending"
  | "detectionUnavailable"
  | "unrecognizedVersion"
  | "detectionBudgetExceeded"
  | "desiredStateObserved"
  | "desiredStateMissing"
  | "cleanupPending"
  | "cleanupUnverified";
/**
 * Closed stop request diagnostics. Neither variant is a termination/effect observation.
 *
 * This interface was referenced by `SelfServiceCommands`'s JSON-Schema
 * via the `definition` "StopOutcome".
 */
export type StopOutcome = "acknowledged" | "failed";

export interface SelfServiceCommands {
  appearance_snapshot: Command4;
  self_service_cancel: Command3;
  self_service_execute: Command2;
  self_service_snapshot: Command;
}
/**
 * This interface was referenced by `SelfServiceCommands`'s JSON-Schema
 * via the `definition` "Command4".
 */
export interface Command4 {
  input: null;
  output: AppearanceSnapshot;
}
/**
 * This interface was referenced by `SelfServiceCommands`'s JSON-Schema
 * via the `definition` "AppearanceSnapshot".
 */
export interface AppearanceSnapshot {
  highContrast: boolean;
  materialEnabled: boolean;
  reducedMotion: boolean;
}
/**
 * This interface was referenced by `SelfServiceCommands`'s JSON-Schema
 * via the `definition` "Command3".
 */
export interface Command3 {
  input: ActionRef;
  output: BackendTaskView;
}
/**
 * This interface was referenced by `SelfServiceCommands`'s JSON-Schema
 * via the `definition` "ActionRef".
 */
export interface ActionRef {
  requestId: RequestId;
}
/**
 * User intent retained in the sole execution journal before a frozen execution exists.
 *
 * This interface was referenced by `SelfServiceCommands`'s JSON-Schema
 * via the `definition` "BackendRequest".
 */
export interface BackendRequest {
  /**
   * Diagnosis when preparation failed.
   */
  failure: BackendRequestFailure | null;
  /**
   * Exact offer and its display summary.
   */
  offer: BackendTask;
  /**
   * Monotonic journal revision.
   */
  revision: number;
  /**
   * Preparation state, separate from execution lifecycle.
   */
  state: BackendRequestState;
  /**
   * OS-authenticated original trigger; never accepted from an IPC request body.
   */
  trigger: BackendTrigger;
}
/**
 * Exact displayed backend offer, without executable input or authorization claims.
 *
 * This interface was referenced by `SelfServiceCommands`'s JSON-Schema
 * via the `definition` "BackendTask".
 */
export interface BackendTask {
  /**
   * Backend attempt identity; reconnect never allocates a new attempt.
   */
  attempt: Id;
  /**
   * Exclusive UTC Unix expiry in seconds.
   */
  expiresAt: number;
  /**
   * Deterministic original execution request used for status after response loss.
   */
  request: RequestId;
  /**
   * Full signed offer revision.
   */
  revision: Digest;
  /**
   * Complete safe action preview, immutable with the offer revision.
   */
  summary: BackendTaskSummary;
  /**
   * Backend task identity.
   */
  task: Id;
  /**
   * Safe display text selected by the backend.
   */
  title: string;
  /**
   * Requires an explicit local user action before requesting Start.
   */
  userInitiated: boolean;
}
/**
 * Exact software coordinate displayed before user confirmation.
 *
 * This interface was referenced by `SelfServiceCommands`'s JSON-Schema
 * via the `definition` "BackendStepSummary".
 */
export interface BackendStepSummary {
  /**
   * Execution account class.
   */
  identity: BackendIdentity;
  /**
   * Exact package selected by the backend.
   */
  package: string;
  /**
   * Exact version; no implicit latest.
   */
  version: string;
}
/**
 * Claimed OS login provenance at the request origin, separate from target and run-as identity.
 *
 * This interface was referenced by `SelfServiceCommands`'s JSON-Schema
 * via the `definition` "OsSessionRef".
 */
export interface OsSessionRef {
  /**
   * Login account at the origin; never implicitly equated to the product actor.
   */
  account: OsAccountRef;
  /**
   * Origin device reference; it does not establish registration or target authority.
   */
  device: DeviceId;
  /**
   * Origin OS login/session reference, including an explicit test reference in fixtures.
   */
  session: Id;
}
/**
 * Opaque account reference in an OS namespace, independent of product or provider identity.
 *
 * This interface was referenced by `SelfServiceCommands`'s JSON-Schema
 * via the `definition` "OsAccountRef".
 */
export interface OsAccountRef {
  /**
   * OS namespace of this reference or target; does not assert platform support.
   */
  platform: Platform;
  /**
   * Opaque stable OS account reference, such as a SID/UID reference, not an authentication credential.
   */
  subject: Id;
}
/**
 * Exact resource/configuration reference. Resolution and authenticity belong to the owner.
 *
 * This interface was referenced by `SelfServiceCommands`'s JSON-Schema
 * via the `definition` "VersionedRef".
 */
export interface VersionedRef {
  /**
   * Opaque reference identity; the revision must be supplied separately.
   */
  id: Id;
  /**
   * Exact immutable revision reference; does not resolve or follow a moving alias.
   */
  revision: Id;
}
/**
 * One authorized record read provides both lifecycle status and frozen plan facts.
 *
 * This interface was referenced by `SelfServiceCommands`'s JSON-Schema
 * via the `definition` "ExecutionTaskDetails".
 */
export interface ExecutionTaskDetails {
  /**
   * Redacted frozen plan bound to that lifecycle.
   */
  action: FrozenExecutionSummary;
  /**
   * Authoritative lifecycle projection.
   */
  status: ExecutionStatus;
}
/**
 * Allowlisted view of the immutable plan; no parameters, launch inputs, secrets or audit.
 *
 * This interface was referenced by `SelfServiceCommands`'s JSON-Schema
 * via the `definition` "FrozenExecutionSummary".
 */
export interface FrozenExecutionSummary {
  /**
   * Restrictions summarized without individual private values.
   */
  access: AccessSummary;
  /**
   * Permission-bearing principal; not the model account.
   */
  actor: ActorId;
  /**
   * Exact artifact revision and content hash.
   */
  artifact: ExactArtifactRef;
  /**
   * Product authority bound to the exact plan.
   */
  authority: Authority;
  /**
   * Cumulative plan budget; retries do not reset it.
   */
  budget: ExecutionBudget;
  /**
   * Digest covers the complete original plan, including omitted private values.
   */
  contentDigest: Digest;
  /**
   * Closed execution kind without private software paths or source inputs.
   */
  execution: ExecutionSummary;
  /**
   * Human or AI origin, without granting execution permission.
   */
  initiator: Initiator;
  /**
   * Exact interpreter selection.
   */
  interpreter: InterpreterRef;
  /**
   * Action and exact resource revision.
   */
  operation: Operation;
  /**
   * Exact policy revision.
   */
  policy: VersionedRef;
  /**
   * Exact frozen plan identity.
   */
  requestId: RequestId;
  /**
   * Explicit execution identity; never inferred from a provider login.
   */
  runAs: RunAs;
  /**
   * Version of the frozen execution plan, independent of the AI wire version.
   */
  schemaVersion: LocalContractV5;
  /**
   * Required target user session.
   */
  sessionRequirement: SessionRequirement;
  /**
   * Explicit device/platform/user target.
   */
  target: Target;
  /**
   * Original validity window.
   */
  validity: ValidityWindow;
}
/**
 * Resource revision and exact SHA-256 content identity; does not itself verify downloaded bytes.
 *
 * This interface was referenced by `SelfServiceCommands`'s JSON-Schema
 * via the `definition` "ExactArtifactRef".
 */
export interface ExactArtifactRef {
  /**
   * Exact resource ID and revision; no latest-version lookup is performed here.
   */
  resource: VersionedRef;
  /**
   * Expected content SHA-256. The adapter must verify the actual bytes before use.
   */
  sha256: Digest;
}
/**
 * Cumulative allowances for the entire plan, never replenished by retries.
 *
 * This interface was referenced by `SelfServiceCommands`'s JSON-Schema
 * via the `definition` "ExecutionBudget".
 */
export interface ExecutionBudget {
  /**
   * Maximum attempts for the whole plan; retries never multiply time/output budgets.
   */
  maxAttempts: number;
  /**
   * Aggregate stdout/stderr/result bytes across all attempts, including discarded output.
   */
  totalOutputBytes: number;
  /**
   * Total elapsed wall time from the first attempt start, including retries/backoff/waits.
   * Pre-execution approval waits are excluded; retries never replenish this budget.
   */
  totalTimeoutMs: number;
}
/**
 * Safe software-step projection from the frozen program.
 *
 * This interface was referenced by `SelfServiceCommands`'s JSON-Schema
 * via the `definition` "SoftwareStepSummary".
 */
export interface SoftwareStepSummary {
  /**
   * Selected closed adapter.
   */
  adapter: SoftwareKind;
  /**
   * Exact backend package.
   */
  package: PackageValue;
  /**
   * Actual execution identity for the step.
   */
  runAs: RunAs;
  /**
   * Fixed package version.
   */
  version: PackageValue;
}
/**
 * Exact binary and immutable calling convention. Neither reference proves availability.
 *
 * This interface was referenced by `SelfServiceCommands`'s JSON-Schema
 * via the `definition` "InterpreterRef".
 */
export interface InterpreterRef {
  /**
   * Binary identity; the adapter must verify bytes, without PATH or version fallback.
   */
  artifact: ExactArtifactRef;
  /**
   * Calling convention identity/revision; matched together with the binary.
   */
  profile: VersionedRef;
}
/**
 * Action and exact resource identity submitted to the authorization owner.
 *
 * This interface was referenced by `SelfServiceCommands`'s JSON-Schema
 * via the `definition` "Operation".
 */
export interface Operation {
  /**
   * Stable operation identifier owned by the catalog/authorization policy.
   */
  action: Id;
  /**
   * Exact resource ID and revision; no latest-version lookup is performed here.
   */
  resource: VersionedRef;
}
/**
 * Explicit device, platform and scope bound into the plan digest.
 *
 * This interface was referenced by `SelfServiceCommands`'s JSON-Schema
 * via the `definition` "Target".
 */
export interface Target {
  /**
   * Explicit device reference in the containing authority/context; not registration evidence.
   */
  device: DeviceId;
  /**
   * OS namespace of this reference or target; does not assert platform support.
   */
  platform: Platform;
  /**
   * Device-wide or explicit-user scope as defined by this type.
   */
  scope: TargetScope;
}
/**
 * UTC Unix milliseconds. The host separately validates current time and revocation freshness.
 *
 * This interface was referenced by `SelfServiceCommands`'s JSON-Schema
 * via the `definition` "ValidityWindow".
 */
export interface ValidityWindow {
  /**
   * Exclusive validity deadline as UTC Unix milliseconds, strictly after the start.
   */
  expiresAtUnixMs: number;
  /**
   * Earliest validity instant as UTC Unix milliseconds; no system clock is consulted here.
   */
  notBeforeUnixMs: number;
}
/**
 * Authorized value-only task projection. Never includes launch, parameters or raw output.
 *
 * This interface was referenced by `SelfServiceCommands`'s JSON-Schema
 * via the `definition` "ExecutionStatus".
 */
export interface ExecutionStatus {
  /**
   * Latest durable, value-only admission decision, independent of prior attempt facts.
   */
  admission: AdmissionStatus | null;
  /**
   * Fixture assessment if recorded; Unknown is not success.
   */
  assessment: EffectAssessment | null;
  /**
   * Current admitted attempt, absent before admission.
   */
  attemptId: AttemptId | null;
  /**
   * Total admitted attempts; retries never reset it.
   */
  attempts: number;
  /**
   * Sticky cancellation request, independently of termination.
   */
  cancelRequested: boolean;
  /**
   * Canonical digest of the complete immutable execution input.
   */
  contentDigest: Digest;
  /**
   * First-delivery diagnosis; never evidence that execution had no effect.
   */
  dispatchCause: DispatchCause | null;
  /**
   * Authorized evidence references only.
   */
  evidence: EvidenceRef[];
  /**
   * Explicit fixture provenance, also present before the first attempt.
   */
  mode: ExecutionMode;
  /**
   * Original reliable business identity.
   */
  operationRequestId: RequestId;
  /**
   * Current derived lifecycle phase.
   */
  phase: TaskPhase;
  /**
   * Redacted process progress, distinct from lifecycle termination and effect proof.
   */
  process: ProcessSummary | null;
  /**
   * Safe independent software diagnostic; observed state is not final success.
   */
  software: SoftwareDiagnostic | null;
  /**
   * Last stop request response; independent of termination/effect evidence.
   */
  stopOutcome: StopOutcome | null;
}
/**
 * Versioned observation reference and runner provenance; the referenced fact remains unverified.
 *
 * This interface was referenced by `SelfServiceCommands`'s JSON-Schema
 * via the `definition` "EvidenceRef".
 */
export interface EvidenceRef {
  /**
   * Recorded observation category; a category label does not prove an external fact.
   */
  kind: EvidenceKind;
  /**
   * Exact versioned reference. Authenticity and access are checked by its owner.
   */
  reference: VersionedRef;
  /**
   * Runner reference whose evidence is being recorded, including an explicit fixture runner in tests.
   */
  runner: Id;
}
/**
 * Ordinary result projection. No raw output, paths, process identifiers or secrets.
 *
 * This interface was referenced by `SelfServiceCommands`'s JSON-Schema
 * via the `definition` "ProcessSummary".
 */
export interface ProcessSummary {
  /**
   * Stop/failure classification.
   */
  end: ProcessEnd;
  /**
   * Root exit code, independently from effect or scope quiescence.
   */
  exitCode: number | null;
  /**
   * First mechanism failure. Required even when no failure has occurred.
   */
  failureKind: ProcessFailureKind;
  /**
   * Root capture completed; not proof of all descendants terminating.
   */
  finished: boolean;
  /**
   * Capture/decoding quality, not a business success bit.
   */
  quality: OutputQuality;
  /**
   * Explicit full-scope proof; false means unproven.
   */
  quiescent: boolean;
  /**
   * Bytes observed including discarded bytes.
   */
  totalOutputBytes: number;
}
/**
 * This interface was referenced by `SelfServiceCommands`'s JSON-Schema
 * via the `definition` "Command2".
 */
export interface Command2 {
  input: BackendSelection;
  output: TaskSubmission;
}
/**
 * A selection references exact backend content and carries no script or local catalog model.
 *
 * This interface was referenced by `SelfServiceCommands`'s JSON-Schema
 * via the `definition` "BackendSelection".
 */
export interface BackendSelection {
  /**
   * Original backend attempt.
   */
  attempt: Id;
  /**
   * Original request shown with the offer, used unchanged for recovery.
   */
  request: RequestId;
  /**
   * Revision shown to the user/model.
   */
  revision: Digest;
  /**
   * Backend task identity.
   */
  task: Id;
}
/**
 * Selection acknowledgement, distinct from persisted execution or effect completion.
 *
 * This interface was referenced by `SelfServiceCommands`'s JSON-Schema
 * via the `definition` "TaskSubmission".
 */
export interface TaskSubmission {
  /**
   * A human still needs to confirm the displayed task in the desktop.
   */
  confirmationRequired: boolean;
  /**
   * Original request to query after a timeout or disconnect.
   */
  request: RequestId;
}
/**
 * This interface was referenced by `SelfServiceCommands`'s JSON-Schema
 * via the `definition` "Command".
 */
export interface Command {
  input: SnapshotQuery;
  output: Snapshot;
}
/**
 * This interface was referenced by `SelfServiceCommands`'s JSON-Schema
 * via the `definition` "SnapshotQuery".
 */
export interface SnapshotQuery {
  after: RequestId | null;
  selected: RequestId | null;
}
/**
 * This interface was referenced by `SelfServiceCommands`'s JSON-Schema
 * via the `definition` "Snapshot".
 */
export interface Snapshot {
  available: BackendTask[];
  next: RequestId | null;
  preparations: BackendRequest[];
  requests: ExecutionTaskDetails[];
  selected: BackendTaskView | null;
}

export type SelfServicePort = {
  [K in keyof SelfServiceCommands as K extends `self_service_${infer M}`
    ? M
    : never]: SelfServiceCommands[K]["input"] extends null
    ? () => Promise<SelfServiceCommands[K]["output"]>
    : (
        input: SelfServiceCommands[K]["input"],
      ) => Promise<SelfServiceCommands[K]["output"]>;
};
