[package]
name = "local-service"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[dependencies]
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
sha2.workspace = true
schemars.workspace = true

[target.'cfg(unix)'.dependencies]
libc = "=0.2.189"

[target.'cfg(windows)'.dependencies]
tokio = { workspace = true, features = ["net", "rt", "time", "macros"] }
windows-sys = { version = "=0.61.2", features = ["Win32_Foundation", "Win32_Security", "Win32_Security_Authorization", "Win32_Security_Cryptography", "Win32_Storage_FileSystem", "Win32_System_IO", "Win32_System_Memory", "Win32_System_Pipes", "Win32_System_Threading", "Win32_System_Services", "Win32_UI_Shell", "Win32_System_Com"] }

[build-dependencies]
cc = "=1.4.5"
