export const steps = [
  [
    "CI runner tests",
    "node",
    [
      "--test",
      "scripts/ci-result.test.mjs",
      "scripts/ci-impact.test.mjs",
      "scripts/ci-plan.test.mjs",
      "scripts/build-run.test.mjs",
      "scripts/cargo-target.test.mjs",
    ],
  ],
  ["frozen dependencies", "pnpm", ["install", "--frozen-lockfile"]],
  ["workspace build inputs", "pnpm", ["-r", "build"]],
  [
    "native service/process generated contracts",
    "node",
    ["scripts/generate-process-contract.mjs", "--check"],
  ],
  [
    "product harness tests",
    "node",
    [
      "--test",
      "scripts/ci-workspace.test.mjs",
      "scripts/service-verification.test.mjs",
      "scripts/desktop-dev.test.mjs",
      "scripts/runtime-integrity.test.mjs",
      "scripts/execution-evolution.test.mjs",
      "scripts/connection-source-results.test.mjs",
      "scripts/ai-contract-evolution.test.mjs",
    ],
  ],
  [
    "desktop native acceptance syntax",
    "node",
    ["--check", "scripts/check-desktop-native.mjs"],
  ],
  [
    "desktop model fixture syntax",
    "node",
    ["--check", "tests/desktop/model-fixture.mjs"],
  ],
  ["AI generated contracts", "pnpm", ["check:ai-contract"]],
  ["AI contract conformance", "pnpm", ["test:ai-contract"]],
  ["AI access conformance", "pnpm", ["test:ai-access"]],
  ["AI access boundaries", "pnpm", ["check:ai-boundaries"]],
  ["AI SQLite recovery", "pnpm", ["test:ai-store"]],
  ["Claude SDK adapter", "pnpm", ["test:ai-claude"]],
  ["AI Host lifecycle", "pnpm", ["test:ai-host"]],
  ["AI Host local runtime", "pnpm", ["bundle:ai-host"]],
  ["Codex pinned protocol", "pnpm", ["check:codex-protocol"]],
  ["Codex native adapter", "pnpm", ["test:ai-codex"]],
  ["DeepSeek Harness adapter", "pnpm", ["test:ai-deepseek"]],
  ["AI provider acceptance", "pnpm", ["test:ai-acceptance"]],
  ["frontend build", "pnpm", ["build"]],
  ["assistant product acceptance", "pnpm", ["check:assistant"]],
  ["types", "pnpm", ["typecheck"]],
  ["frontend format", "pnpm", ["format:check"]],
  ["components", "pnpm", ["test"]],
  ["boundaries", "pnpm", ["check:boundaries"]],
  ["docs and diff", "node", ["scripts/check-docs.mjs"]],
  ["rust fmt", "cargo", ["fmt", "--all", "--", "--check"]],
  ["rust build", "cargo", ["build", "--workspace", "--locked"]],
  ["rust test", "cargo", ["test", "--workspace", "--locked"]],
  [
    "native driver authentication",
    "cargo",
    [
      "test",
      "--locked",
      "-p",
      "rss-mdm-desktop",
      "-p",
      "tauri-plugin-wdio-webdriver",
      "--features",
      "rss-mdm-desktop/native-e2e",
      "--lib",
      "every_request_requires_the_exact_run_capability",
    ],
  ],
  ["self-service fixtures", "node", ["scripts/check-self-service.mjs"]],
  [
    "rust clippy",
    "cargo",
    [
      "clippy",
      "--workspace",
      "--all-targets",
      "--locked",
      "--",
      "-D",
      "warnings",
    ],
  ],
];
