use execution_contract::{decode_plan, FrozenPlan, PlanLimits};

fn limits() -> PlanLimits {
    PlanLimits {
        max_input_bytes: 65536,
        max_depth: 32,
        max_nodes: 4096,
        max_string_bytes: 4096,
        max_collection_items: 128,
        max_timeout_ms: 60000,
        max_output_bytes: 65536,
        max_attempts: 3,
    }
}

#[test]
fn plan_is_frozen_from_validated_data() {
    let plan = decode_plan(include_bytes!("fixtures/plan.json"), &limits()).unwrap();
    let frozen = FrozenPlan::freeze(plan, &limits()).unwrap();
    assert_eq!(frozen.digest().as_str().len(), 64);
    assert!(!format!("{frozen:?}").contains("example.invalid"));
}

#[test]
fn duplicate_parameters_and_untrusted_fields_are_rejected() {
    let source = include_str!("fixtures/plan.json");
    for input in [
        source.replace("\"host\": {", "\"host\": {}, \"host\": {"),
        source.replacen("{", "{\"authorized\":true,", 1),
        source.replacen("\"schemaVersion\": 1", "\"schemaVersion\": 2", 1),
    ] {
        assert!(decode_plan(input.as_bytes(), &limits()).is_err());
    }
}

#[test]
fn budgets_and_numbers_cannot_be_silently_truncated() {
    let source = include_str!("fixtures/plan.json");
    for input in [
        source.replace("\"totalTimeoutMs\": 1000", "\"totalTimeoutMs\": 60001"),
        source.replace("\"maxAttempts\": 1", "\"maxAttempts\": 0"),
        source.replace(
            "\"value\": \"example.invalid\"",
            "\"value\": 9007199254740993",
        ),
    ] {
        assert!(decode_plan(input.as_bytes(), &limits()).is_err());
    }
}

fn fixture() -> serde_json::Value {
    serde_json::from_str(include_str!("fixtures/plan.json")).unwrap()
}
fn freeze(value: &serde_json::Value) -> FrozenPlan {
    FrozenPlan::freeze(
        decode_plan(&serde_json::to_vec(value).unwrap(), &limits()).unwrap(),
        &limits(),
    )
    .unwrap()
}
#[test]
fn independent_digest_vector_and_order_invariance() {
    let frozen = freeze(&fixture());
    assert_eq!(
        frozen.digest().as_str(),
        include_str!("fixtures/plan.sha256").trim()
    );
    let compact = serde_json::to_vec(&fixture()).unwrap();
    assert_eq!(
        FrozenPlan::freeze(decode_plan(&compact, &limits()).unwrap(), &limits())
            .unwrap()
            .digest(),
        frozen.digest()
    );
    let source = include_str!("fixtures/plan.json").replace(
        "\"kind\": \"literal\",\n        \"value\": \"example.invalid\"",
        "\"value\": \"example.invalid\",\n        \"kind\": \"literal\"",
    );
    assert_ne!(source, include_str!("fixtures/plan.json"));
    assert_eq!(
        FrozenPlan::freeze(
            decode_plan(source.as_bytes(), &limits()).unwrap(),
            &limits()
        )
        .unwrap()
        .digest(),
        frozen.digest()
    );
}
#[test]
fn every_valid_security_leaf_is_covered_by_the_digest() {
    fn changes(v: &serde_json::Value, path: String, out: &mut Vec<(String, serde_json::Value)>) {
        use serde_json::{json, Value};
        match v {
            Value::Object(o) => {
                for (k, v) in o {
                    changes(
                        v,
                        format!("{path}/{}", k.replace('~', "~0").replace('/', "~1")),
                        out,
                    );
                }
            }
            Value::Array(a) => {
                for (i, v) in a.iter().enumerate() {
                    changes(v, format!("{path}/{i}"), out);
                }
            }
            Value::String(s) if !path.ends_with("/kind") && !path.ends_with("/platform") => {
                let replacement = if path.ends_with("/sha256") {
                    "23".repeat(32)
                } else {
                    format!("{s}-changed")
                };
                out.push((path, json!(replacement)));
            }
            Value::Number(n) if !path.ends_with("/schemaVersion") => {
                out.push((path, json!(n.as_u64().unwrap() + 1)))
            }
            Value::Bool(b) => out.push((path, json!(!b))),
            _ => {}
        }
    }
    let original = fixture();
    let expected = freeze(&original);
    let mut cases = Vec::new();
    changes(&original, String::new(), &mut cases);
    // Independent fields, not an expected serialization string generated by the implementation.
    assert!(cases.iter().any(|(p, _)| p == "/request/actor"));
    assert!(cases.iter().any(|(p, _)| p == "/launch/interpreter/sha256"));
    assert!(cases
        .iter()
        .any(|(p, _)| p == "/request/parameters/credential/reference/revision"));
    for (path, value) in cases {
        let mut modified = original.clone();
        *modified.pointer_mut(&path).unwrap() = value;
        assert_ne!(
            freeze(&modified).digest(),
            expected.digest(),
            "unbound field {path}"
        );
    }
    let mut modified = original;
    modified["launch"]["argv"] = serde_json::json!(["example.invalid", "--host"]);
    assert_ne!(freeze(&modified).digest(), expected.digest());
}
#[test]
fn namespaces_and_initiators_remain_distinct() {
    let original = fixture();
    let digest = freeze(&original).digest().clone();
    for authority in [
        serde_json::json!({"kind":"local","id":"test-authority"}),
        serde_json::json!({"kind":"enterprise","id":"test-authority","tenant":"tenant-1"}),
    ] {
        let mut v = original.clone();
        v["request"]["authority"] = authority;
        assert_ne!(freeze(&v).digest(), &digest);
    }
    for initiator in [
        serde_json::json!({"kind":"ai","provider":"provider-1","conversation":"c-1","toolCall":"tc-1","osSession":fixture()["request"]["initiator"]["osSession"],"providerAccount":{"account":"provider-user-1","config":{"id":"config-1","revision":"1"}}}),
        serde_json::json!({"kind":"policy","policy":{"id":"p-1","revision":"1"}}),
    ] {
        let mut v = original.clone();
        v["request"]["initiator"] = initiator;
        assert_ne!(freeze(&v).digest(), &digest);
    }
}
#[test]
fn nested_unknowns_ids_paths_and_execution_context_fail_closed() {
    use serde_json::json;
    for (path, value) in [
        ("/request/actor", json!("")),
        (
            "/request/authority",
            json!({"kind":"test","id":"a","trusted":true}),
        ),
        (
            "/request/initiator",
            json!({"kind":"human","approved":true}),
        ),
        ("/launch/interpreter/sha256", json!("latest")),
        ("/launch/cwd", json!("relative/path")),
        ("/launch/cwd", json!("/root/../other")),
        ("/launch/argv", json!(["bad\u{0}arg"])),
        (
            "/launch/env",
            json!({"BAD=NAME":{"kind":"literal","value":"x"}}),
        ),
        ("/runAs", json!({"kind":"system","platform":"windows"})),
        (
            "/constraints/network",
            json!({"kind":"allowlist","destinations":["*"]}),
        ),
        ("/validity/expiresAtUnixMs", json!(1000)),
    ] {
        let mut v = fixture();
        *v.pointer_mut(path).unwrap() = value;
        assert!(
            decode_plan(&serde_json::to_vec(&v).unwrap(), &limits()).is_err(),
            "{path}"
        );
    }
    for literal in [
        "9007199254740992",
        "9007199254740993.0",
        "-9007199254740992",
        "1e400",
        "NaN",
    ] {
        let source = include_str!("fixtures/plan.json").replace(
            "\"value\": \"example.invalid\"",
            &format!("\"value\": {literal}"),
        );
        assert!(
            decode_plan(source.as_bytes(), &limits()).is_err(),
            "{literal}"
        );
    }
}
#[test]
fn bounds_cover_bytes_strings_depth_collections_nodes_and_budget() {
    let bytes = include_bytes!("fixtures/plan.json");
    let l = limits();
    let cases = [
        PlanLimits {
            max_input_bytes: bytes.len() - 1,
            ..l
        },
        PlanLimits {
            max_string_bytes: 63,
            ..l
        },
        PlanLimits { max_depth: 3, ..l },
        PlanLimits { max_nodes: 5, ..l },
        PlanLimits {
            max_collection_items: 1,
            ..l
        },
        PlanLimits {
            max_output_bytes: 4095,
            ..l
        },
        PlanLimits {
            max_timeout_ms: 999,
            ..l
        },
        PlanLimits {
            max_attempts: 0,
            ..l
        },
    ];
    for limit in cases {
        assert!(decode_plan(bytes, &limit).is_err());
    }
    let exact = PlanLimits {
        max_input_bytes: bytes.len(),
        max_timeout_ms: 1000,
        max_output_bytes: 4096,
        max_attempts: 1,
        ..l
    };
    assert!(decode_plan(bytes, &exact).is_ok());
    let mut plan = decode_plan(bytes, &l).unwrap();
    plan.budget.total_timeout_ms = 60001;
    assert!(FrozenPlan::freeze(plan, &l).is_err());
}
#[test]
fn numeric_normalization_and_immutable_snapshot() {
    let mut value = fixture();
    value["request"]["parameters"]["host"]["value"] = serde_json::json!(-0.0);
    let negative = freeze(&value);
    value["request"]["parameters"]["host"]["value"] = serde_json::json!(0);
    let zero = freeze(&value);
    assert_eq!(negative.digest(), zero.digest());
    assert_eq!(negative.spec(), zero.spec());
    let mut copy = zero.spec().clone();
    copy.launch.argv.push("modified".into());
    assert_ne!(
        FrozenPlan::freeze(copy, &limits()).unwrap().digest(),
        zero.digest()
    );
    assert!(!zero.matches_digest(&execution_contract::Digest::new("00".repeat(32)).unwrap()));
}
#[test]
fn audit_references_are_correlated_without_secret_material_or_real_test_effects() {
    use execution_contract::decode_audit;
    let source = include_bytes!("fixtures/audit.json");
    let audit = decode_audit(source, &limits()).unwrap();
    assert_eq!(
        audit.plan_digest.as_str(),
        include_str!("fixtures/plan.sha256").trim()
    );
    assert_eq!(
        serde_json::to_value(audit).unwrap(),
        serde_json::from_slice::<serde_json::Value>(source).unwrap()
    );
    for kind in ["processExited", "stateObserved"] {
        let source = std::str::from_utf8(source)
            .unwrap()
            .replace("testResult", kind);
        assert!(decode_audit(source.as_bytes(), &limits()).is_err());
    }
}
#[test]
fn schema_snapshots_accept_goldens_and_reject_structural_bypasses() {
    let schemas = serde_json::json!({"plan":execution_contract::plan_schema(),"audit":execution_contract::audit_schema()});
    let expected: serde_json::Value =
        serde_json::from_str(include_str!("fixtures/schemas.json")).unwrap();
    assert_eq!(schemas, expected);
    for (schema, mut value) in [
        ("plan", fixture()),
        (
            "audit",
            serde_json::from_str(include_str!("fixtures/audit.json")).unwrap(),
        ),
    ] {
        let validator = jsonschema::validator_for(&schemas[schema]).unwrap();
        assert!(validator.is_valid(&value));
        value["authorized"] = true.into();
        assert!(!validator.is_valid(&value));
    }
    let validator = jsonschema::validator_for(&schemas["plan"]).unwrap();
    let mut bad = fixture();
    bad["request"]["initiator"]["trusted"] = true.into();
    assert!(!validator.is_valid(&bad));
}

#[test]
fn direct_dto_deserialization_cannot_hide_duplicate_parameter_or_literal_keys() {
    let source = include_str!("fixtures/plan.json");
    for bad in [
        source.replace("\"host\": {", "\"host\": {}, \"host\": {"),
        source.replace(
            "\"value\": \"example.invalid\"",
            "\"value\": {\"a\":1,\"a\":2}",
        ),
    ] {
        assert!(serde_json::from_str::<execution_contract::PlanSpec>(&bad).is_err());
    }
}

#[test]
fn typed_decode_errors_retain_owned_classification_without_input_values() {
    use execution_contract::decode_audit;
    let source = include_str!("fixtures/plan.json");
    for (old, new, expected) in [
        (
            "\"schemaVersion\": 1",
            "\"schemaVersion\": 999",
            execution_contract::ErrorKind::UnsupportedVersion,
        ),
        (
            "\"actor\": \"actor-1\"",
            "\"actor\": \"private invalid actor\"",
            execution_contract::ErrorKind::InvalidValue,
        ),
    ] {
        let bad = source.replacen(old, new, 1);
        let error = decode_plan(bad.as_bytes(), &limits()).unwrap_err();
        assert_eq!(error.kind(), expected);
        assert!(!error.to_string().contains("private"));
    }
    let bad = include_str!("fixtures/audit.json").replacen(
        "\"schemaVersion\": 1",
        "\"schemaVersion\": 999",
        1,
    );
    assert_eq!(
        decode_audit(bad.as_bytes(), &limits()).unwrap_err().kind(),
        execution_contract::ErrorKind::UnsupportedVersion
    );
    assert_eq!(
        decode_plan(b"{", &limits()).unwrap_err().kind(),
        execution_contract::ErrorKind::Encoding
    );
}
#[test]
fn observed_audit_requires_attempt_and_evidence() {
    let source: serde_json::Value =
        serde_json::from_str(include_str!("fixtures/audit.json")).unwrap();
    let mut no_attempt = source.clone();
    no_attempt["decision"]["attemptId"] = serde_json::Value::Null;
    let mut no_evidence = source;
    no_evidence["decision"]["evidence"] = serde_json::json!([]);
    for invalid in [no_attempt, no_evidence] {
        assert!(execution_contract::decode_audit(
            &serde_json::to_vec(&invalid).unwrap(),
            &limits()
        )
        .is_err());
    }
}

#[test]
fn additional_attempts_do_not_multiply_total_plan_budgets() {
    let mut value = fixture();
    value["budget"]["maxAttempts"] = 3.into();
    let accepted = freeze(&value);
    assert_eq!(accepted.spec().budget.total_timeout_ms, 1000);
    assert_eq!(accepted.spec().budget.total_output_bytes, 4096);
    for (field, over) in [("totalTimeoutMs", 60001u64), ("totalOutputBytes", 65537)] {
        let mut bad = value.clone();
        bad["budget"][field] = over.into();
        assert!(decode_plan(&serde_json::to_vec(&bad).unwrap(), &limits()).is_err());
    }
    let mut legacy = value;
    legacy["budget"]
        .as_object_mut()
        .unwrap()
        .remove("totalTimeoutMs");
    legacy["budget"]["timeoutMs"] = 1000.into();
    assert!(decode_plan(&serde_json::to_vec(&legacy).unwrap(), &limits()).is_err());
}
